### ISSUE TITLE
请问LicenseServer新的地址在哪呢

### ISSUE THREAD

**Issue by Tzeao** [Nasller/CodeGlancePro#101]
1. Which Glance version and IDEA version?

2. Could you show Glance config picture and minimap picture?

3. What steps will reproduce the issue?

**Comment by Nasller** [comment]
https://notabug.org/Nasller/LicenseServer

**Comment by meiMingle** [comment]
> https://notabug.org/Nasller/LicenseServer

新地址噶了
![image](https://github.com/Nasller/CodeGlancePro/assets/39942874/e288b3fc-b6b5-47c2-8400-63ee76a744c2)
