### ISSUE TITLE
[题外篇] Tab着色有没有心情研究一下

### ISSUE THREAD

**Issue by sdhzwc** [Nasller/CodeGlancePro#103]
类似这种 https://github.com/tobszarny/ActiveTabHighlighterPlugin.git

**Comment by Nasller** [comment]
这玩意儿我记得不用插件呀

**Comment by sdhzwc** [comment]
> 这玩意儿我记得不用插件呀

![image](https://github.com/Nasller/CodeGlancePro/assets/46134044/0fb7e5ff-9645-4ffa-aede-694e2199ff45)
idea 不带这种的

**Comment by Nasller** [comment]
![image](https://github.com/Nasller/CodeGlancePro/assets/26132153/ca0b96c1-5a2f-4447-8f08-027f9920e945)
不用插件

**Comment by sdhzwc** [comment]
> ![image](https://github.com/Nasller/CodeGlancePro/assets/26132153/ca0b96c1-5a2f-4447-8f08-027f9920e945)
> 不用插件,颜色也可以换,不过如果用的新UI的话，效果有点不如旧UI

底部有一条颜色杠杠，不如整个名字进行着色更醒目！

**Comment by Nasller** [comment]
你是想让它跑起来还是维护它？维护它的话我就没太多时间了。

**Comment by sdhzwc** [comment]
> 你是想让它跑起来还是维护它？维护它的话我就没太多时间了。

只是探讨有没有价值 不需要维护的

**Comment by Nasller** [comment]
> > 你是想让它跑起来还是维护它？维护它的话我就没太多时间了。
> 
> 只是探讨有没有价值 不需要维护的

这种就是你喜欢的话，可以自己研究一下，按道理说这种功能官方已经有就没必要再搞了。
