### ISSUE TITLE
[BUG] Exception in CodeGlancePro 1.5.5

### ISSUE THREAD

**Issue by brentcameron5** [Nasller/CodeGlancePro#108]
<img width="409" alt="Screenshot 2023-10-04 at 9 07 16 AM" src="https://github.com/Nasller/CodeGlancePro/assets/109082925/9bdd1edf-2369-41eb-89df-3cf71c0f9533">

<img width="985" alt="Screenshot 2023-10-04 at 9 06 59 AM" src="https://github.com/Nasller/CodeGlancePro/assets/109082925/8ac38d8e-78b1-4f72-8c31-cc6c1f7b2a1d">

Full error:

> decoding of (38,74) failed for PsiElement(XML_ATTRIBUTE_VALUE) : [43, -1] inSegment = [5, 36]
> 
> java.lang.Throwable
> 	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:192)
> 	at com.intellij.psi.util.PartiallyKnownString$mapRangeToHostRange$1.invoke(PartiallyKnownString.kt:201)
> 	at com.intellij.psi.util.PartiallyKnownString.mapRangeToHostRange(PartiallyKnownString.kt:234)
> 	at com.intellij.psi.util.PartiallyKnownString.rangeForSubElement(PartiallyKnownString.kt:86)
> 	at com.intellij.psi.util.PartiallyKnownString.buildSegmentWithMappedRange(PartiallyKnownString.kt:91)
> 	at com.intellij.psi.util.PartiallyKnownString.splitAtInKnown(PartiallyKnownString.kt:111)
> 	at com.intellij.microservices.url.references.UrlPksParser.p(UrlPksParser.kt:109)
> 	at com.intellij.microservices.url.references.UrlPksParser.parseUrlPath(UrlPksParser.kt:129)
> 	at com.intellij.microservices.url.references.UrlPathReferenceInjector.buildReferences(UrlPathReferenceInjector.kt:125)
> 	at com.intellij.javascript.microservices.HtmlUrlPathReferenceAsFileReferenceProvider.createReferences(HtmlUrlPathReferenceAsFileReferenceProvider.kt:31)
> 	at com.intellij.openapi.paths.PathReferenceProviderBase.createReferences(PathReferenceProviderBase.java:45)
> 	at com.intellij.openapi.paths.PathReferenceManagerImpl.processProvider(PathReferenceManagerImpl.java:260)
> 	at com.intellij.openapi.paths.PathReferenceManagerImpl.createReferences(PathReferenceManagerImpl.java:101)
> 	at com.intellij.openapi.paths.PathReferenceManagerImpl.createReferences(PathReferenceManagerImpl.java:83)
> 	at com.intellij.htmltools.xml.util.HtmlReferenceProvider.getReferencesByElement(HtmlReferenceProvider.java:262)
> 	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:199)
> 	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:162)
> 	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:141)
> 	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
> 	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
> 	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
> 	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
> 	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
> 	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
> 	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
> 	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
> 	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
> 	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
> 	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
> 	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:80)
> 	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:90)
> 	at com.intellij.javascript.web.codeInsight.css.classes.WebSymbolCssClassInHtmlReferenceProvider.getOffsetsToSymbols(WebSymbolCssClassInHtmlReferenceProvider.kt:15)
> 	at com.intellij.javascript.web.codeInsight.css.classes.WebSymbolCssClassInHtmlReferenceProvider.getOffsetsToSymbols(WebSymbolCssClassInHtmlReferenceProvider.kt:10)
> 	at com.intellij.javascript.web.codeInsight.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:53)
> 	at com.intellij.javascript.web.codeInsight.WebSymbolReferenceProvider.access$getReferences(WebSymbolReferenceProvider.kt:30)
> 	at com.intellij.javascript.web.codeInsight.WebSymbolReferenceProvider$getReferences$1.compute(WebSymbolReferenceProvider.kt:35)
> 	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
> 	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
> 	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
> 	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
> 	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
> 	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
> 	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
> 	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
> 	at com.intellij.javascript.web.codeInsight.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:33)
> 	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.doGetExternalReferences(PsiSymbolReferenceServiceImpl.java:68)
> 	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:45)
> 	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:38)
> 	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:34)
> 	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
> 	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:276)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
> 	at com.nasller.codeglance.visitor.MyRainbowVisitor.analyze(MyRainbowVisitor.kt:16)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
> 	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:606)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
> 	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
> 	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
> 	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
> 	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> 
>

**Comment by Nasller** [comment]
upgrade your ide or ignore this error log
