### ISSUE TITLE
[BUG]Code thumbnail graphics are sometimes large and sometimes small

### ISSUE THREAD

**Issue by meiMingle** [Nasller/CodeGlancePro#110]
1. Which Glance version and IDEA version?
IDEA 2023.2.2
CodeGlancePro 1.7.5
3. Could you show Glance config picture and minimap picture?
![CodeGlancePro.gif](https://github.com/Nasller/CodeGlancePro/assets/39942874/02f4417d-060c-4966-93f5-59f5d9d37c28)

4. What steps will reproduce the issue?
Open a file with a large number of lines of code (more than 100 lines) and slowly scroll the mouse wheel.

**Comment by Nasller** [comment]
Unable to reproduce this issue
