### ISSUE TITLE
[BUG]小地图不显示代码，只显示高亮

### ISSUE THREAD

**Issue by SIceAex** [Nasller/CodeGlancePro#117]
1. Which Glance version and IDEA version?
2023.3
2. Could you show Glance config picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/128665694/0fcb9425-7ea3-4dec-b805-f1f682a782e3)
3. What steps will reproduce the issue?

**Comment by Nasller** [comment]
这不是我这次新加的特性吗，你开了吧
![image](https://github.com/Nasller/CodeGlancePro/assets/26132153/21d3f31c-7a98-4f94-a3eb-23dc8e75982a)

**Comment by SIceAex** [comment]
没错刚注意到，习惯只开主编译器的小地图，每次更新都重新去取消掉其他的，没注意看，误会误会

**Comment by Nasller** [comment]
兄弟没必要跟他喷了，那个我提交删除删掉了评论

**Comment by SIceAex** [comment]
应该也有不少邮件发到你那了，见谅见谅
