### ISSUE TITLE
[BUG] 启用 console 的小地图，会导致 logcat 设置面板的预览无法正常显示

### ISSUE THREAD

**Issue by Vixb1122** [Nasller/CodeGlancePro#118]
1. Which Glance version and IDEA version?
Android Studio Iguana | 2023.2.1 Beta 2
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.nasller.CodeGlancePro (1.7.6)

2. Could you show Glance config picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/17810492/2c4174cf-fe9c-4c81-a659-f4f81281c609)
![image](https://github.com/Nasller/CodeGlancePro/assets/17810492/d45138bc-0245-4e34-a39a-60eb91b5c1d5)
3. What steps will reproduce the issue?
启用 console 小地图，正常界面应该是这样的：
![image](https://github.com/Nasller/CodeGlancePro/assets/17810492/72281d19-6a40-4d4a-9769-d7ccb39cf3cf)

**Comment by Nasller** [comment]
![image](https://github.com/Nasller/CodeGlancePro/assets/26132153/62403bed-dce0-4c8c-83f7-7d5d2ca51154)
不知是否与版本有关
