### ISSUE TITLE
[IMPROVEMENT] Highlights all the textual matches of token at the caret location in the Scrollbar

### ISSUE THREAD

**Issue by FrederikKoers** [Nasller/CodeGlancePro#119]
Hi,
In Visual Studio I'm used to seeing the selected text highlighted and all matches in in the scrollbar, unfortunately I couldn't find the same feature in IntelliJ.

Would this be a good improvement or have I just not seen this option?

**Comment by Nasller** [comment]
As far as I know, this effect has been realized in the plugin. Select the text to highlight or display the current line to highlight.

**Comment by FrederikKoers** [comment]
![image](https://github.com/Nasller/CodeGlancePro/assets/44230153/7fc3a908-bbc8-44cb-9c6f-4c2f38d965a4)
Sorry forgot to add the info about all matches of the selected text in the scrollbar. 
Like here with VS and https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MatchMargin

**Comment by Nasller** [comment]
As far as I know, this function is similar to the search text highlighting and identifier under caret highlighting in ide. You only need to modify the color in the color scheme. This function has also been implemented in the plugin.

**Comment by Nasller** [comment]
I probably understand what you mean, because there is no function of selecting text to search in ide, so I can't highlight it.

**Comment by FrederikKoers** [comment]
You were right, the color in the dark color design just had not enough contrast to make it visible.
thank you for the fast help
