### ISSUE TITLE
[BUG] Incompatable with PHPStorm 241 EAP despite changelog stating otherwise

### ISSUE THREAD

**Issue by reganjohnson** [Nasller/CodeGlancePro#122]
1. Which Glance version and IDEA version?
Glance: `1.8.1`
IDEA: `241.**` / `2024.1 EAP`

2. Could you show Glance config picture and minimap picture?
No

3. What steps will reproduce the issue?
Unable to install on latest EAP due to incompatibility despite changelog referencing 241 EAP support (requires version <= 233)

![capture-2024-02-22-073623](https://github.com/Nasller/CodeGlancePro/assets/12020344/976ee0d0-8aca-4161-8070-e55c5b196877)

I did find the `CodeGlance_Pro-1.8.1-SNAPSHOT-2024-02-18T16-09-signed` which installs correctly manually, but not working through plugin marketplace.

Thanks for your work on this project!

**Comment by Nasller** [comment]
Please see README EAP Version, and add EAP plugin channel to ide
