### ISSUE TITLE
[BUG] With gitlab plugin, when i review with Diff, it dispaly uncorrectly

### ISSUE THREAD

**Issue by EatARainbow** [Nasller/CodeGlancePro#128]
1. Which Glance version and IDEA version?
Glance version: 1.8.2, Pycharm Community Edition: 2023.3.5
2. Can you show the complete config page picture and minimap picture?
![2024-04-02_18-43](https://github.com/Nasller/CodeGlancePro/assets/124040941/1eddda56-75b2-40b9-8b5f-a87a6578c49c)
![2024-04-02_18-44](https://github.com/Nasller/CodeGlancePro/assets/124040941/dde4f47b-9458-4f9b-bb92-e60105744960)

3. What is the file type used and provide text or an example of the issue that occurred?
.py
4. What steps will reproduce the issue?
Show Diff by GitLab plugin

**Comment by Nasller** [comment]
Is this the official plugin?

**Comment by jamievlin** [comment]
Also happening with github code reviews. Official plugin, 2024.1 (241.14494.240)

**Comment by Nasller** [comment]
![image](https://github.com/Nasller/CodeGlancePro/assets/26132153/519953ff-8a8b-4ecf-9b4c-a71d255bf6cb)
This seems to be a strange behavior of the official plugin, which has a scrollbar but cannot be used, causing minimap to fail to run

**Comment by Nasller** [comment]
And the scroll bar used by the plugin is the one inside, so this issue cannot be fixed temporarily
