### ISSUE TITLE
[BUG] Clippping with new "Sticky lines" in PHPStorm 2024.1

### ISSUE THREAD

**Issue by etshy** [Nasller/CodeGlancePro#129]
1. Which Glance version and IDEA version?
Glance : 1.8.3-241
PHPStorm 2024.1 - PS-241.14494.237

2. Can you show the complete config page picture and minimap picture?
Glance config is the default
Can't really show the issue as it happens when scrolling, The Sticky line and minimap are hiding each others and clipping.

3. What is the file type used and provide text or an example of the issue that occurred?
Noticed on a PHP and twig file but should happen on files.

4. What steps will reproduce the issue?
Open a file wiht enough line to scroll and scroll, you'll see the clipping happening in top right corner

**Comment by Nasller** [comment]
download the lastest EAP version

**Comment by etshy** [comment]
On `1.8.4-SNAPSHOT-2024-04-14T14-50`, it seems to be fixed, I didn't get any clipping for the past 10 or so minutes.

Thx for the fix
