### ISSUE TITLE
[建议] 延时判断是否显示快速预览窗口

### ISSUE THREAD

**Issue by lddtime** [Nasller/CodeGlancePro#13]
PhpStorm 2022.1 MacOS

当我使用两个屏幕工作时，鼠标总是在两个屏幕间移动。
只要鼠标经过了代码小地图，**即便速度很快，也会触发预览窗口**。
我觉得只需 100～200ms 左右的延迟，就可以改善这种现象。

不知道是否好修改，只是个建议。😁

**Comment by Nasller** [comment]
ok,我考虑下
