### ISSUE TITLE
[BUG] Console minimap does not work after I update IDEA to 2024.1.2

### ISSUE THREAD

**Issue by WaitAKennyJ** [Nasller/CodeGlancePro#132]
1. Which Glance version and IDEA version?
1.8.5; 2024.1.2
2. Can you show the complete config page picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/34837904/e9868a85-cc30-4227-9261-74be7e7d3446)

3. What is the file type used and provide text or an example of the issue that occurred?

4. What steps will reproduce the issue?

**Comment by Nasller** [comment]
Show your config?

**Comment by WaitAKennyJ** [comment]
![image](https://github.com/Nasller/CodeGlancePro/assets/34837904/e1b98e4b-28c9-4db1-ac00-def4e6bf2eff)

**Comment by WaitAKennyJ** [comment]
@Nasller

**Comment by Nasller** [comment]
show the 'Editor kind' config
