### ISSUE TITLE
[Feature Request] Render characters

### ISSUE THREAD

**Issue by paulverbeke** [Nasller/CodeGlancePro#134]
Hi,

Thank you for this awesome plugin. This should be definitely natively implemented in jetbrains IDE.
I was wondering if it could be possible de render the characters like in VS and VS Code ?

Without rendering:
![image](https://github.com/Nasller/CodeGlancePro/assets/6412153/12112b72-77a8-497e-9f1f-cc01edf333fb)
![image](https://github.com/Nasller/CodeGlancePro/assets/6412153/be227f08-a455-4846-b1d9-dc90278d3ae6)

With rendering:
![image](https://github.com/Nasller/CodeGlancePro/assets/6412153/813eff38-d0b2-4044-a762-9970d6192a1c)

Thanks !

**Comment by Nasller** [comment]
it already has a config.called the render style in config settings.
