### ISSUE TITLE
[Feature Request] Add support for #region

### ISSUE THREAD

**Issue by paulverbeke** [Nasller/CodeGlancePro#135]
Hi,

Would you be opened to implement or accept a PR to support for dotnet #region like VS Code ?
![image](https://github.com/Nasller/CodeGlancePro/assets/6412153/f8b67b12-732a-4886-9c98-d55853e5f417)

I suppose we only need to change the default value of the Mark regex ?

Thanks

**Comment by Nasller** [comment]
sure,i can accept a PR to support it.

**Comment by paulverbeke** [comment]
Does your current regex only applies in comments ?

**Comment by Nasller** [comment]
yes,sir

**Comment by paulverbeke** [comment]
So I've made a simple PR to update the default regex to handle region comment (like requested in #79) but I suppose adding support for #region in C# will be harder because it is not a comment

**Comment by Nasller** [comment]
I guess we need to find its specific type in the parse tree.The type of comment in the parse tree is `com.intellij.psi.PsiComment`.
You can try use psiViewer plugin to find it. Parsing it requires great caution as this class is executed very frequently `com.nasller.codeglance.extensions.visitor.MarkCommentVisitor`

**Comment by Nasller** [comment]
hello sir, you can test this feature on EAP version now.

**Comment by paulverbeke** [comment]
great thanks a lot !
The behavior looks not consistent, here's some examples:

1. Not all regions are rendered, and those that are are hard to read with the green bar in the background
![image](https://github.com/user-attachments/assets/56614c2b-40bc-4653-bb7b-a0eb1fd3b12e)![image](https://github.com/user-attachments/assets/ae8a27ac-f8bc-4528-9c3c-ca5828c335da)
2. I can make UserRights region render if there's 2 blank lines before 
![image](https://github.com/user-attachments/assets/80d248a1-e26d-4948-b030-66130baf4447)![image](https://github.com/user-attachments/assets/d31a1be3-3372-4be4-868c-787ae2c83d72)

**Comment by Nasller** [comment]
2. Yes, because the highlighted text will cover the pixels below, so if the two highlighted text segments are too close, they will be overwritten, which is inevitable.

**Comment by Nasller** [comment]
1. Because there has warning errors to be solved in the text, it will conflict with other functions of the plugin(filter markup highlight). There is no good way to solve this problem at present.

**Comment by paulverbeke** [comment]
> 2. Yes, because the highlighted text will cover the pixels below, so if the two highlighted text segments are too close, they will be overwritten, which is inevitable.

that's unfortunate, because the standard use of #region won't be covered by this feature: in C# we don't put several blank lines between statements or regions, at the most 1 line. Here there's still a missing region:
![image](https://github.com/user-attachments/assets/29a19379-9153-4cd7-bb0b-fd7fd0d78245)
![image](https://github.com/user-attachments/assets/1d401e90-8e64-4169-bb29-e942eb405c9a)

**Comment by Nasller** [comment]
> > 2. Yes, because the highlighted text will cover the pixels below, so if the two highlighted text segments are too close, they will be overwritten, which is inevitable.
> 
> that's unfortunate, because the standard use of #region won't be covered by this feature: in C# we don't put several blank lines between statements or regions, at the most 1 line. Here there's still a missing region: ![image](https://private-user-images.githubusercontent.com/6412153/368511127-29a19379-9153-4cd7-bb0b-fd7fd0d78245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjM2NTAsIm5iZiI6MTcyNjcyMzM1MCwicGF0aCI6Ii82NDEyMTUzLzM2ODUxMTEyNy0yOWExOTM3OS05MTUzLTRjZDctYmIwYi1mZDdmZDBkNzgyNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDUyMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI2OWJjYjg5YjQyZjI1NjI2ZDU1MDUxMDExMjVhODg5NjNjNWIzNzJjMWQ0ZDU4OWRkNmRiMWYyMTQzMmU1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XWdmmpSfD3ZSuuecWWxWpQl2u7UvC4VTb7GTElZi9UY) ![image](https://private-user-images.githubusercontent.com/6412153/368511788-1d401e90-8e64-4169-bb29-e942eb405c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjM2NTAsIm5iZiI6MTcyNjcyMzM1MCwicGF0aCI6Ii82NDEyMTUzLzM2ODUxMTc4OC0xZDQwMWU5MC04ZTY0LTQxNjktYmIyOS1lOTQyZWI0MDVjOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDUyMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI5MWUwYWJkNWNlODQ0YzBiMDVmMzY0NWYzOTQ0Y2ViNzEyYTMxNmY2OWM5ZmQzODhlYTkzM2IyMGUwYjk3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SS_JXmEQ9wM1whhtSZ80DT7gn40PoG2LVV0ujHaADjg)

sorry sir, i cannot handle this at present.
