### ISSUE TITLE
[BUG] Running Crash Error

### ISSUE THREAD

**Issue by yangxianshen1993** [Nasller/CodeGlancePro#138]
1. Which Glance version and IDEA version?
PHPstorm 2024.1.1
2. Can you show the complete config page picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/142369081/0810ae3b-d89f-4c3d-8651-0760fe898ecf)
3. What is the file type used and provide text or an example of the issue that occurred?
php log  txt
4. What steps will reproduce the issue?
When the map is turned on, the laravel9 framework code reports an error, and file changes may occur when writing logs. Then phpstrom crashed.

**Comment by Nasller** [comment]
can you show the error txt?
