### ISSUE TITLE
老哥能出一个超过多少行就默认关闭的功能吗？

### ISSUE THREAD

**Issue by hprof** [Nasller/CodeGlancePro#14]
代码超过1w行就开始卡了，打字都拖泥带水的

**Comment by Nasller** [comment]
好的，我看看有啥办法解决下

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.2.zip](https://github.com/Nasller/CodeGlancePro/files/8568783/CodeGlance.Pro-1.3.2.zip)
试下，配置在设置里，minLineCount，超过了就会关掉

**Comment by hprof** [comment]
不行啊老哥，我修改了框里的数字然后点击空白区域似乎并没有侦测到改动（因为侦测到的话Apply就会亮起），而且我鼠标焦点选择到其他文本框的时候，Minimum lines count文本框里的数字又变成了100,000，包括文本框里右边的那俩上下调整箭头也不奏效

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.2.zip](https://github.com/Nasller/CodeGlancePro/files/8569262/CodeGlance.Pro-1.3.2.zip)
试试这个

**Comment by hprof** [comment]
可以了，非常感谢！GitHub贡献了一个小星星，希望可以在下一个版本作为正式功能推出

**Comment by Nasller** [comment]
好的谢谢
