### ISSUE TITLE
[BUG]在2024.2版本不工作了

### ISSUE THREAD

**Issue by iwillmissu** [Nasller/CodeGlancePro#140]
1. Which Glance version and IDEA version?
2024.2
2. Can you show the complete config page picture and minimap picture?
默认的配置并未做修改
3. What is the file type used and provide text or an example of the issue that occurred?
更新idea到2024.2版本
4. What steps will reproduce the issue?
更新idea版本到2024.2

**Comment by Nasller** [comment]
等2024.2 Publish了之后更新，暂时可以先用EAP
