### ISSUE TITLE
[BUG] Incompatible with IntelliJ 2024.2

### ISSUE THREAD

**Issue by cloudshiftchris** [Nasller/CodeGlancePro#141]
1. Which Glance version and IDEA version?

IntelliJ 2024.2

3. Can you show the complete config page picture and minimap picture?

No; the plugin fails to load: `Incompatible: requires IDE build 241.* or earlier` (plugin version 1.8.5)

5. What is the file type used and provide text or an example of the issue that occurred?

n/a

7. What steps will reproduce the issue?

Attempt to install plugin on IntelliJ 2024.2

**Comment by Nasller** [comment]
Released, awaiting Jetbrains approval
