### ISSUE TITLE
Feature request: Show bookmark names on the minimap like markers

### ISSUE THREAD

**Issue by amadeusmz** [Nasller/CodeGlancePro#145]
It would be nice to be able to use bookmarks as minimap markers

**Comment by Nasller** [comment]
i will consider it

**Comment by Nasller** [comment]
please try the lastest EAP version. https://plugins.jetbrains.com/plugin/18824-codeglance-pro/versions/eap

**Comment by amadeusmz** [comment]
@Nasller 
That was fast!
The new feature worked, 感謝！
