### ISSUE TITLE
[BUG] Incompatible: requires IDE build 242.* or earlier

### ISSUE THREAD

**Issue by bpsbits-org** [Nasller/CodeGlancePro#149]
## Which Glance version and IDEA version?

- Glance 1.9.0
- WebStorm 2024.3 EAP (`Build #WS-243.12818.48, built on September 11, 2024`)

## Can you show the complete config page picture and minimap picture?

- Minimap does not work at all due the incompatibility 

## What is the file type used and provide text or an example of the issue that occurred?

- Javascript

## What steps will reproduce the issue?

- Update WebStorm to 2024.3 EAP

**Comment by karolskolasinski** [comment]
Plugin 'CodeGlance Pro' (version '1.9.2') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is WS-243.20847.31

**Comment by Nasller** [comment]
![image](https://github.com/user-attachments/assets/742cd56c-1325-46ab-9da9-54939f94c257)
![image](https://github.com/user-attachments/assets/e72e7ef8-10b4-434d-b3e1-f9f47a7fea82)

please add EAP channel to the custom plugin repositories, so that you can receive plugin update notification.

**Comment by ArtsiomCh** [comment]
Thanks, I know that way, but it have few cons:

1. Users don't see any EAP until they manually do that subscription
2. EAP channel updates supersede the stable channel according to JB docs

Why not to have EAP version right in the stable channel? It want affect stable ide version users but when they update their ide they automatically get EAP plugin.
I do that for my plugins and it works like a charm.

**Comment by Nasller** [comment]
Because I don’t want to switch development back and forth between different plugin versions, but I can release an EAP-compatible version once and not update its functions until exiting the official version. I will consider it.

**Comment by 0x1f57** [comment]
> ![image](https://private-user-images.githubusercontent.com/26132153/383370968-742cd56c-1325-46ab-9da9-54939f94c257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjEwOTMsIm5iZiI6MTczMTQ2MDc5MywicGF0aCI6Ii8yNjEzMjE1My8zODMzNzA5NjgtNzQyY2Q1NmMtMTMyNS00NmFiLTlkYTktNTQ5MzlmOTRjMjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAxMTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MTE3NDZjNjQzMTRhM2MzZWFkM2YzMmUxZGZmNGM0NDRkODMzNjY1MGMyMzQxZTFkMTNiMWNkZTAxYTFkODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.32rQGdOhMHsqxjVE_g019l2MDzn0dBPC2-Q4kf4-ntw) ![image](https://private-user-images.githubusercontent.com/26132153/383371066-e72e7ef8-10b4-434d-b3e1-f9f47a7fea82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjEwOTMsIm5iZiI6MTczMTQ2MDc5MywicGF0aCI6Ii8yNjEzMjE1My8zODMzNzEwNjYtZTcyZTdlZjgtMTBiNC00MzRkLWIzZTEtZjlmNDdhN2ZlYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAxMTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDRlMzE2MDY5ZTQ0ZWRkOWJlODIyYWFiNmEwZjlkNGFmNTRkZTQ0M2QzZmFmZTAyNjY2Mzc2ODMwYWY2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7iQ8z1ya_K7ckfjOr4ue-X5pCvzW8mOaJf7iAkbcEto)
> 
> please add EAP channel to the custom plugin repositories, so that you can receive plugin update notification.

Webstorm 2024.3 stable version has been released. Please release the corresponding adapted version

**Comment by Nasller** [comment]
done
