### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by combobo** [Nasller/CodeGlancePro#15]
hi, **in Webstorm, cannot coexist with [React Buddy] Plugin.**, After installing [React Buddy], it will not display.

**Comment by combobo** [comment]
and is covered by the `background image`

**Comment by Nasller** [comment]
can provide a small project?

**Comment by Nasller** [comment]
It should be that he is not a native editor, so this kind of problem occurs. I can't adapt all the plug -ins. They all use different editors. It is difficult for me to adapt

**Comment by Nasller** [comment]
if you want to support the plugin,you can submit a PR,thanks
