### ISSUE TITLE
[BUG] Glance color scheme replace normal color scheme

### ISSUE THREAD

**Issue by vfyjxf** [Nasller/CodeGlancePro#151]
1. Which Glance version and IDEA version?
Glance:1.9.1 IDEA 2024.2.3
2. Can you show the complete config page picture and minimap picture?
No

3. What is the file type used and provide text or an example of the issue that occurred?

file type: .java problem: glance color scheme(Class name) replace normal color scheme.
4. What steps will reproduce the issue?
![image](https://github.com/user-attachments/assets/90db431a-7a07-4b50-a013-74e6ca7cc2bf)
![image](https://github.com/user-attachments/assets/7f8f6674-f05d-4ca4-8323-ccbb492c5c79)

**Comment by vfyjxf** [comment]
normal color scheme:
![image](https://github.com/user-attachments/assets/c0fabbaf-1239-4d43-bf67-e37cb02c4c9b)

**Comment by Nasller** [comment]
https://plugins.jetbrains.com/plugin/18824-codeglance-pro/versions/eap
please try use the lastest EAP version

**Comment by vfyjxf** [comment]
eap版本没问题了
