### ISSUE TITLE
Plugin does not appear (CodeGlance Pro) in Android Studio Latest

### ISSUE THREAD

**Issue by Sofyan232** [Nasller/CodeGlancePro#154]
Plugin does not appear (CodeGlance Pro) - https://plugins.jetbrains.com/plugin/18824-codeglance-pro
I used the previous version, this plugin appeared. After I updated to the latest version of Android Studio, this plugin had problems as shown in this photo
![Screenshot_20241028_100906](https://github.com/user-attachments/assets/ee093ffe-e06b-47fd-8233-769ff72236ad)

OS : Ubuntu 24.10
Build: AI-242.23339.11.2421.12483815, 202410110354
**AS: Ladybug | 2024.2.1 Patch 1**
AI-242.23339.11.2421.12483815, JRE 17.0.12+8-LTS-286x64 Oracle Corporation, OS Linux(amd64) v6.11.0-9-generic, screens 1366x768 (100%)
Gradle JDK: Oracle OpenJDK 17.0.12
NDK: from local.properties: (not specified), latest from SDK: 27.1.12297006
CMake: from local.properties: (not specified), latest from SDK: 3.30.5, from PATH: 3.30.3

**Comment by Nasller** [comment]
check your setting page, do you disable it?
![image](https://github.com/user-attachments/assets/b22c0452-0465-4e1b-a976-a39009157e88)

**Comment by Sofyan232** [comment]
I can't open settings. continuously like this.
![Screenshot_20241031_124043](https://github.com/user-attachments/assets/5abf177e-108d-4dcf-858e-67a15efcc256)
**Log Android Studio Latest :** [idea.log](https://github.com/user-attachments/files/17582141/idea.log)
I have reported this to the Android Studio team but they told me to contact the plugin developer, namely you. android studio team can't fix this

**Comment by Nasller** [comment]
i see, The reason for this is that the jdk version used by Android Studio is 17, but the plugin version uses 21

**Comment by Nasller** [comment]
![image](https://github.com/user-attachments/assets/06bacf65-2f8c-4b2c-bba6-14ef83588425)

**Comment by Sofyan232** [comment]
Fixed with :
Android Studio Ladybug | 2024.2.1 Patch 1
Build #AI-242.23339.11.2421.12483815, built on October 11, 2024
**Runtime version: 21.0.5+9-LTS-239 amd64**
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Toolkit: sun.awt.X11.XToolkit
Linux 6.11.0-9-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation

THANKS !
