### ISSUE TITLE
[BUG] C# Region Text color super bright green and not configurable

### ISSUE THREAD

**Issue by mikerochip** [Nasller/CodeGlancePro#155]
1. Which Glance version and IDEA version?
Glance 1.9.2
JetBrains Rider 2024.2.7

This is the About page with some work stuff deleted:

Build #RD-242.23726.100, built on October 22, 2024
Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
.NET Core v8.0.4 ARM64 (Server GC)
JetBrains IDE Services version: 2024.4.0.8991-ij242
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.nasller.CodeGlancePro (1.9.2)

2. Can you show the complete config page picture and minimap picture?

<img width="322" alt="image" src="https://github.com/user-attachments/assets/54b82c19-ca64-4570-8301-2e148358965f">
<img width="204" alt="image" src="https://github.com/user-attachments/assets/5f0a766c-6cdb-44f4-abfa-318fcd09a52b">

I thought changing the "Viewport Border Color" would affect this, but it doesn't seem to be the case.

<img width="817" alt="image" src="https://github.com/user-attachments/assets/b49098fa-1f54-4746-a292-4dfee3698c7e">

3. What is the file type used and provide text or an example of the issue that occurred?

Any `.cs` file

4. What steps will reproduce the issue?

Make a `#region Foobar` for example, in any C# file

I use the Rider Dark color scheme. I've had to disable CodeGlance for now because my team uses `#region` a lot and the color of region names are so bright in the editor that it makes my eyes hurt. I don't mind the region name colors in the minimap, but in the editor, the contrast is too intense and it's too bright.

This is what region names look like without the bright green, it is a dimmer light gray

<img width="271" alt="image" src="https://github.com/user-attachments/assets/12a9bbcd-e852-42fc-9ee2-4403cb0176a6">

**Comment by Nasller** [comment]
[CodeGlancePro-1.9.3-SNAPSHOT-2024-11-04T13-26-signed.zip](https://github.com/user-attachments/files/17614077/CodeGlancePro-1.9.3-SNAPSHOT-2024-11-04T13-26-signed.zip)
try this, now you can modify the mark line color by errorstrip color in color settings page

**Comment by Nasller** [comment]
![image](https://github.com/user-attachments/assets/86154ff2-9ee2-44e1-9037-903baf352af2)
