### ISSUE TITLE
[BUG] its not work on android studio lady bug patch 2

### ISSUE THREAD

**Issue by salahshms** [Nasller/CodeGlancePro#156]
1. Which Glance version and IDEA version?

2. Can you show the complete config page picture and minimap picture?

3. What is the file type used and provide text or an example of the issue that occurred?

4. What steps will reproduce the issue?

**Comment by Nasller** [comment]
![image](https://github.com/user-attachments/assets/a2c320a3-d427-487e-a252-5835f6973c08)
what does not work?

**Comment by pRizo-jpeg** [comment]
Its also not showing here on this Android Studio Build, I guess it might be related to android studio ladybug being shipped with Java 21, as when I did swap it to 18 It (presumably) stopped working


Android Studio Ladybug | 2024.2.1 Patch 2

Build #AI-242.23339.11.2421.12550806, built on October 24, 2024
Runtime version: 18.0.2.1+1-1 aarch64

VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Toolkit: sun.lwawt.macosx.LWCToolkit

macOS 15.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.vecheslav.darculaDarkerTheme (1.2.0)
  Dart (242.22855.32)
  com.nasller.CodeGlancePro (1.9.3)
  com.github.copilot (1.5.29.7524)
  io.flutter (82.1.3)

**Comment by Nasller** [comment]
please see #154
