### ISSUE TITLE
[BUG] Plugin "CodeGlance Pro" was not installed: Request failed with status code 403

### ISSUE THREAD

**Issue by komatebe** [Nasller/CodeGlancePro#158]
1. Which Glance version and IDEA version?

2. Can you show the complete config page picture and minimap picture?

3. What is the file type used and provide text or an example of the issue that occurred?

4. What steps will reproduce the issue?

**Comment by komatebe** [comment]
I can't install the plugin. I get the following popup error msg on instal: Plugin "CodeGlance Pro" was not installed: Request failed with status code 403
(PyCharm 2024.3 Pro)

**Comment by Nasller** [comment]
check your network? or you can download this.
[CodeGlancePro-1.9.4-signed.zip](https://github.com/user-attachments/files/17953220/CodeGlancePro-1.9.4-signed.zip)
