### ISSUE TITLE
[BUG] // MARK: -  doesn't showup in the minimap

### ISSUE THREAD

**Issue by clearskystudio** [Nasller/CodeGlancePro#159]
1. Which Glance version and IDEA version?
Glance 1.9.4  Rider 2024.3

2. Can you show the complete config page picture and minimap picture?
![image](https://github.com/user-attachments/assets/27fb029d-66a3-4a35-8822-0bf9818c222f)
![image](https://github.com/user-attachments/assets/b72f4d02-a4ab-4b96-a1b1-07e03131f72b)

3. What is the file type used and provide text or an example of the issue that occurred?
C# code mark tags don't show up in the minimap 

4. What steps will reproduce the issue?
Add "// MARK: - text", see nothing in the minimap

**Comment by Nasller** [comment]
can you copy the marker regex in the settings?

**Comment by clearskystudio** [comment]
\b(MARK: - )\b|\b(MARK: )\b|(?:region \b)
Haven't touched that I think

**Comment by Nasller** [comment]
![QQ截图20241206200951](https://github.com/user-attachments/assets/14fb6550-6c34-487c-aa07-ac06985e6189)
check this settings, it must set color

**Comment by clearskystudio** [comment]
It worked! Thanks!
