### ISSUE TITLE
[BUG] Minimap not showing collapsed custom folding regions

### ISSUE THREAD

**Issue by rala72** [Nasller/CodeGlancePro#16]
1. Which Glance version and IDEA version?
Glance: 1.3.2 _(but happens also earlier)_
IJ: IU-221.5080.210

2. Do you enabled reader mode option?
no

3. Could you show Glance config picture and minimap picture?
sure
![image](https://user-images.githubusercontent.com/6838669/165594793-208eab2e-306b-49a5-8cf7-a62f97eac87b.png)

4. What steps will reproduce the issue?

Add custom folding regions and collapse them.
Nothing will be shown in minimap (see screenshot above).
At least a green line would be nice.

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.3.zip](https://github.com/Nasller/CodeGlancePro/files/8579237/CodeGlance.Pro-1.3.3.zip)
check for this
color setting in color scheme fold text foreground

**Comment by rala72** [comment]
will you do a public release for it?

**Comment by Nasller** [comment]
yeah.i will
