### ISSUE TITLE
What is the role of the Python code?

### ISSUE THREAD

**Issue by meiMingle** [Nasller/CodeGlancePro#2]
Hello, I am learning the source code of your project. I would like to ask what is the function of the Python code in it? I did not find the content compiled by the Python code in the plug-in compressed package downloaded from the plug-in market.

**Comment by Nasller** [comment]
In fact, there is no python code. This should be universal.

**Comment by meiMingle** [comment]
> In fact, there is no python code. This should be universal.
OK， thanks for the reply.

**Comment by meiMingle** [comment]
> In fact, there is no python code. This should be universal.

OK,thanks for the reply.
