### ISSUE TITLE
[Question/Request] Dynamic height fixed at 100% of window height?

### ISSUE THREAD

**Issue by AaronV** [Nasller/CodeGlancePro#22]
I'm posting here to ask if you've already tried to do this, or if it's possible.

The feature is something like this. The height of the code-preview is always 100% of the height of the code-window, and all of the document is also always visible, stretched (or squished) to take up 100% of the window height. The scrollbar height and preview-highlight section would always line up, and the preview window never scrolled on it's own. I suppose preview line-height would need to be dynamic.

I've attached a video of what it does that I'm not fond of, the preview scrolls too, showing more or less of the bottom of the document.

What do you think?

https://user-images.githubusercontent.com/17026/166950640-7e4f5d3c-4b71-4c96-86a1-3d497a174d2b.mov

**Comment by Nasller** [comment]
If the picture does not scroll, it will mean that the pixels need to be reduced. 1 pixel is the lowest, and it is impossible to display all the

**Comment by Nasller** [comment]
If the picture does not scroll, it will mean that the pixels need to be reduced. 1 pixel is the lowest, and it is impossible to display all the images in the window.

**Comment by Nasller** [comment]
Code with a large number of rows must be considered

**Comment by AaronV** [comment]
Yes, I can see how it would be bad for some use-cases, especially very long files.

I'd love to see the option along with the other fixed line-heights. Like:

**Pixels Per Line:** [Dynamic, 1, 2, 3, 4]

Is dynamic line-height at a sub-pixel scale possible?

**Comment by Nasller** [comment]
sorry,hard to work
