### ISSUE TITLE
 [Feature Request] Show minimap on the left side of the editor window.

### ISSUE THREAD

**Issue by renebaeu** [Nasller/CodeGlancePro#25]
First of all, I love your plugin. 

And I have a feature request to make it even better for my usage.

Story: With a 34'' display, the editor window is so wide with a single file open, that the distance the Minimap is quite far. Thus, I lose the focus on what i was looking, because I have to navigate the mouse to the Minimap.

Request: Is it possible to make an option to show the minimap on the left side of the editor?

**Comment by renebaeu** [comment]
Another Idea: Navigate in the minimap by holding the middle mouse button  or some button press while in the editor.

**Comment by Nasller** [comment]
> Another Idea: Navigate in the minimap by holding the middle mouse button  or some button press while in the editor.
> 
> 
this has official plugin.see this https://plugins.jetbrains.com/plugin/12388-fast-mouse-scrolling

**Comment by Nasller** [comment]
If minimap is placed on the left, some functions will become strange. And it can only be placed on the left side of the navigation bar.

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/170202597-e1ff8cf4-c4f4-45c5-98e3-fab38433640e.png)
can you accept this?

**Comment by renebaeu** [comment]
absolutely, that looks amazing

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.7.zip](https://github.com/Nasller/CodeGlancePro/files/8769423/CodeGlance.Pro-1.3.7.zip)
try it

**Comment by renebaeu** [comment]
One question to the middle mouse topic. I am not sure if it is possible at all. 

Hold the middle mouse button and scroll the viewport in the minimap. 

The different to the fast mouse plugin will be, that the scroll distance is absolut not relative to our current position. So it would possible to click and move the viewport to the specific position. It would be just more concrete

**Comment by renebaeu** [comment]
The minimap on the left side is amazing. Thank you for that.

**Comment by krasnovpro** [comment]
Can you add this feature to the main branch as an option?
