### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by linmii** [Nasller/CodeGlancePro#26]
1. Which Glance version and IDEA version?
    IDEA 2022.1.1/ Datagrip 2022.1.4 最新版本
    Glance 1.3.6.1

3. Do you enabled reader mode option?
    已开启，但是在Datagrip中未使用文档注释

5. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/17309471/170502645-ed68f424-b5db-41be-9db3-5c59441fbd92.png)
![image](https://user-images.githubusercontent.com/17309471/170502693-0258ba59-9246-4bd4-ba9a-78b898caf3e4.png)

6. What steps will reproduce the issue?
    开启自动换行(软换行)后，编辑器中有较多的自动换行代码，导致底部有很大的空白部分

**Comment by Nasller** [comment]
自动换行啊，这个问题不好解决

**Comment by linmii** [comment]
> 自动换行啊，这个问题不好解决

我也是感觉应该不太好解决，只是问一下，万一能处理呢😄

**Comment by Nasller** [comment]
它和那个inlayhit以及reader mode的问题一样，先凑合用下吧😬

**Comment by Nasller** [comment]
hello，可以帮我验证下吗

**Comment by linmii** [comment]
IDEA和Datagrip测试都没问题，大佬NB

**Comment by Nasller** [comment]
好的，谢谢
