### ISSUE TITLE
[建议]有两个小小的建议

### ISSUE THREAD

**Issue by WangJincheng4869** [Nasller/CodeGlancePro#27]
1. Which Glance version and IDEA version?
IntelliJ IDEA 2022.1.2 (Ultimate Edition)
2. Do you enabled reader mode option?

3. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/41162158/172518895-5623e244-c154-470f-b4ff-789830f8504b.png)
4. What steps will reproduce the issue?
一、当代码达到4000+的时候会导致IDE的明显卡顿，滚动代码卡顿。目前的解决方案是当代码超过2000行不显示map。如果能优化是最好的。
二、如果装了中文插件之后，能否设置页面也显示为中文（不是很重要）

**Comment by Nasller** [comment]
ide不会卡顿，卡的是在滚动，因为文件在analysis

**Comment by WangJincheng4869** [comment]
> ide不会卡顿，卡的是在滚动，因为文件在analysis

编写代码也会有明显的卡顿，打字会有延迟...

**Comment by Nasller** [comment]
嗯，这个和源插件的实现方式有关，他那种写一下就刷新一次的方式就注定文件越长越慢，之前已经考虑过了，实现上有点困难

**Comment by WangJincheng4869** [comment]
> 嗯，这个和源插件的实现方式有关，他那种写一下就刷新一次的方式就注定文件越长越慢，之前已经考虑过了，实现上有点困难

看是否能降低加载频率，比如换行后刷新，或者换行几次后刷新，或者插入多少字符后再刷新。不知道能否监听到删除行操作，或者总行数改变的操作。

**Comment by Nasller** [comment]
应该可以检测到行数变更，只是这么做感觉治标不治本

**Comment by WangJincheng4869** [comment]
> 应该可以检测到行数变更，只是这么做感觉治标不治本

是的，能小幅度提升一下性能。根本感觉还是应该优化生成map的消耗。

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.8.zip](https://github.com/Nasller/CodeGlancePro/files/8863157/CodeGlance.Pro-1.3.8.zip)
hello,有空帮忙试下这个，滚动应该比之前好点了，图片可能变化较小

**Comment by WangJincheng4869** [comment]
> [CodeGlance Pro-1.3.8.zip](https://github.com/Nasller/CodeGlancePro/files/8863157/CodeGlance.Pro-1.3.8.zip) hello,有空帮忙试下这个，滚动应该比之前好点了，图片可能变化较小

滚动时的确有略微的缓解，但是依旧卡顿。编写代码时依旧存在延迟。

**Comment by Nasller** [comment]
没办法，那个minimap一时半会儿改不了
