### ISSUE TITLE
About Minimap Performance Discussion

### ISSUE THREAD

**Issue by Nasller** [Nasller/CodeGlancePro#28]

**Comment by WangJincheng4869** [comment]
我的能力有限，没有进行过插件相关的开发，所以只能大概说一下自己的看法：
1. 能否实现局部渲染。即：当编辑后不是将map整体全部渲染，而是仅渲染修改部分。（如果目前已经是这种形式，那我也想不到更好的方式了）
2. 如果局部渲染无法实现，那基本是无解了，除非官方能给出更好的对接接口。我发现在VS Code中四千行代码毫无压力，这也可能是因为它更加精简的原因，并不是它的map渲染算法更好

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.9.zip](https://github.com/Nasller/CodeGlancePro/files/8885693/CodeGlance.Pro-1.3.9.zip)
有空帮忙试试这个效果，延迟设置行数配置在config里

**Comment by WangJincheng4869** [comment]
> [CodeGlance Pro-1.3.9.zip](https://github.com/Nasller/CodeGlancePro/files/8885779/CodeGlance.Pro-1.3.9.zip) 有空帮忙试试这个效果，延迟设置行数配置在config里

4800+行代码，经过测试，已经有较大改善，但是编辑代码时依旧会有些许卡顿，滚动已经没有之前的卡顿现象

**Comment by Nasller** [comment]
嗯嗯感谢

**Comment by bluelovers** [comment]
能不能設計成在渲染未完成的時候 不會導致無法捲動?

**Comment by Nasller** [comment]
> 能不能設計成在渲染未完成的時候 不會導致無法捲動?

不行，minimap的渲染需要使用ui线程，sdk的一些方法必须使用ui线程才能访问，比如soft wrap

**Comment by Nasller** [comment]
大家有空的话可以帮我测试下新的fast minimap，这将加快小地图的渲染
[CodeGlance Pro-1.6.8-signed.zip](https://github.com/Nasller/CodeGlancePro/files/12248574/CodeGlance.Pro-1.6.8-signed.zip-与市场上传的一致)

**Comment by Nasller** [comment]
> 感覺沒問題

有没有快一点

**Comment by bluelovers** [comment]
目前沒有打開檔案時卡住的感覺

**Comment by Nasller** [comment]
[CodeGlance Pro-1.6.8-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/12266965/CodeGlance.Pro-1.6.8-SNAPSHOT.zip)
用空试试这个，大幅减轻UI线程的阻塞
