### ISSUE TITLE
[BUG] Context menu long load when open file is empty

### ISSUE THREAD

**Issue by slightlyfaulty** [Nasller/CodeGlancePro#29]
**Which Glance version and IDEA version?**
  
CodeGlance Pro 1.3.8
PhpStorm 2022.1.1 Build #PS-221.5591.58

**Do you enabled reader mode option?**
  
Don't know what this is or if it applies.

**Could you show Glance config picture and minimap picture?**

![screenshot-20220613-192244](https://user-images.githubusercontent.com/2036475/173409827-891a5488-ddda-42f2-86cd-290e3be50fcb.png)

**What steps will reproduce the issue?**

1. Create a blank file and open it in the editor.
2. Right-click on a folder in the project panel. A loader shows for a few seconds before the context menu opens.
3. Left-click inside editor, then right-click. A loader shows for a few seconds before the context menu opens.
4. Disable CodeGlance or open a non-empty file. Context menu opens instantly in both cases above.

![Peek 2022-06-13 19-38](https://user-images.githubusercontent.com/2036475/173412356-a5d67425-0e04-4b6f-bae7-3485e59a521a.gif)

**Comment by Nasller** [comment]
thanks report,please try this
[CodeGlance Pro-1.3.9.zip](https://github.com/Nasller/CodeGlancePro/files/8895678/CodeGlance.Pro-1.3.9.zip)

**Comment by slightlyfaulty** [comment]
Yup it looks like that fixes it. Thanks for the quick patch!
