### ISSUE TITLE
[建议]代码错误、警告等的高亮着色要突出一点

### ISSUE THREAD

**Issue by YiiGuxing** [Nasller/CodeGlancePro#33]
代码错误、警告时编辑器滚动条的位置是有突出标记的，虽然小地图内也有标记，但是并不是很突出，不容易找到，且没有警告的标记。
个人的建议是：
1. 警告也需要在小地图内也突出标记；
2. 错误、警告的标记还要突出一点，让人一眼就能分辨出来，最好是整行标记。

![image](https://user-images.githubusercontent.com/10737066/176838337-7e68717b-1956-4b46-91af-43cefa15a8fc.png)
如图中的标记，一但把滚动条隐藏之后，就很难从小地图上定位错误位置了。

**Comment by Nasller** [comment]
嗯，之前之所以没做整行有两个考虑点，一是会和vcs冲突(隐藏滚动条就不会)，二是整行的话如果出现一行两个错误可能显示不全。这个地方还是要想下怎么做才好。我一般都用F2所以没太注意 :)
