### ISSUE TITLE
Hide minimap by default

### ISSUE THREAD

**Issue by viruseg** [Nasller/CodeGlancePro#34]
How do I make the mini map be hidden by default? I've looked through all the settings and this option is missing. Add it please. Or tell me where it can be enabled?

Show minimap on scrollbar hover is not the same. I need an option that does the same thing as the eye button (hide minimap). But as a default option for all tabs.

**Comment by Nasller** [comment]
ctrl shift g? it will invoke all

**Comment by Nasller** [comment]
emmm.but some file have not the eye button.This is a jetbrains extension point.how to show this file?

**Comment by viruseg** [comment]
Maybe make Ctrl-shift-g not disable the "button with the eye (hide minimap)". I.e. leave everything as it is, but do not hide this button.

**Comment by Nasller** [comment]
ok,i will try.

**Comment by viruseg** [comment]
Thank you so much. Your plugin is the best.

**Comment by Nasller** [comment]
please check this. 
[CodeGlance Pro-1.4.4.zip](https://github.com/Nasller/CodeGlancePro/files/9047429/CodeGlance.Pro-1.4.4.zip)

**Comment by viruseg** [comment]
Perfect. Just what I needed. Thank you so much.

**Comment by viruseg** [comment]
There is a bug. When minimap is disabled with Ctrl-shift-g. I click on "Show minimap" button, but it is empty or only part of content is rendered. There are graphic artifacts when you try to scroll.

https://user-images.githubusercontent.com/919215/177381021-c7f263f6-de9f-4af8-b388-3f733dcf9674.mp4


https://user-images.githubusercontent.com/919215/177381105-8b1835d2-bbcf-4a63-af48-06794545d627.mp4

**Comment by viruseg** [comment]
Also, I can't resize the viewport with the mouse. In the settings, the lock is turned off.

**Comment by viruseg** [comment]
Also, sometimes the viewport is not fully displayed.

https://user-images.githubusercontent.com/919215/177433700-e0aaeac3-a679-495c-b8a4-a5d32f26bc14.mp4

**Comment by Nasller** [comment]
> Also, I can't resize the viewport with the mouse. In the settings, the lock is turned off. This happens if you split the window into several parts
> 
> 
> 
> https://user-images.githubusercontent.com/919215/177434224-281a21f0-21b3-45c6-b12e-bf504ea30586.mp4
> 
> 
> 
> .

This is a feature, because the width is automatically calculated in spilt, I don't want it to be modified.

**Comment by Nasller** [comment]
other two bug will fix

**Comment by viruseg** [comment]
At first glance, everything looks great. The bugs that I described above - fixed. Thank you. You are incredibly fast in responding.
