### ISSUE TITLE
[BUG] minimap highlight the wrong position

### ISSUE THREAD

**Issue by lty2008one** [Nasller/CodeGlancePro#35]
like this
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/52694802/177472728-920bca74-697f-4b4a-a132-beed220635d1.png">

**Comment by Nasller** [comment]
这个问题和inlayHit有关，暂时无法解决，你可以将inlayhit的设置更改下，将会得到缓解
![image](https://user-images.githubusercontent.com/26132153/177473014-63afe0cd-c94c-4299-b7fb-d99bc3d05531.png)

**Comment by lty2008one** [comment]
@Nasller see the notes left of the scroll bar

**Comment by Nasller** [comment]
Duplicate of #7

**Comment by lty2008one** [comment]
> 这个问题和inlayHit有关，暂时无法解决，你可以将inlayhit的设置更改下，将会得到缓解
> ![image](https://user-images.githubusercontent.com/26132153/177473014-63afe0cd-c94c-4299-b7fb-d99bc3d05531.png)

感谢🙏
