### ISSUE TITLE
Sync theme with IDE

### ISSUE THREAD

**Issue by kolbasa** [Nasller/CodeGlancePro#36]
Would it be possible to change the colors automatically from Light to Dark and vice versa when changing the theme of the IDE?
Currently you have to disable and re-enable the plugin for the colors to change.

**Comment by Nasller** [comment]
restart?

**Comment by Nasller** [comment]
[CodeGlance Pro-1.4.4.zip](https://github.com/Nasller/CodeGlancePro/files/9061000/CodeGlance.Pro-1.4.4.zip)
check on this

**Comment by kolbasa** [comment]
Oh, wow. I didn't expect that.
I have been annoyed by the behavior for many years. Not specifically with your plugin (I discovered yours only yesterday).
I meant all the CodeGlance forks before that.

It works fantastic, you are the best!

![Theme](https://user-images.githubusercontent.com/3901582/177713506-f986cccc-dca4-4761-98fe-18a43b74e3dc.gif)

**Comment by Nasller** [comment]
okay,thanks
