### ISSUE TITLE
[FEATURE] Add support for click and drag

### ISSUE THREAD

**Issue by ChristopherHaws** [Nasller/CodeGlancePro#37]
Hello and thanks for this plugin which I use everyday!

In the current version of the plugin, you can click and drag (up and down) the minimap slider. If you click anywhere within the minimap panel outside of the slider, it jumps to that location but does not allow you to drag the slider up and down. This makes it so I have to click the location I want, and then click the slider again to scroll up and down. Visual Studio Code and Sublime Text's minimap allows you to click and drag anywhere within the minimap. I would love for this ability to be added to CodeGlance Pro.

CodeGlancePro
![CodeGlance Minimap](https://user-images.githubusercontent.com/5934505/177889143-b818333a-84d1-4df8-a607-767416a5d0d1.gif)

VS Code
![VSCode Minimap](https://user-images.githubusercontent.com/5934505/177889151-69dfca07-0456-4279-aaab-747deaff270f.gif)

Thanks!

**Comment by Nasller** [comment]
[CodeGlance Pro-1.4.5.zip](https://github.com/Nasller/CodeGlancePro/files/9068611/CodeGlance.Pro-1.4.5.zip)
hello,check on this

**Comment by ChristopherHaws** [comment]
Works like a charm! :) Thanks!

**Comment by ryerrappa** [comment]
Hi @Nasller. This works great but it seems like there is a different behavior when clicking and dragging somewhere. The first click moves the editing caret to that new location. Is it possible to add a setting where we can choose whether to move the caret to that location, or just move the viewing window?

**Comment by Nasller** [comment]
> Hi @Nasller. This works great but it seems like there is a different behavior when clicking and dragging somewhere. The first click moves the editing caret to that new location. Is it possible to add a setting where we can choose whether to move the caret to that location, or just move the viewing window?

sure，wait a minute

**Comment by Nasller** [comment]
> Hi @Nasller. This works great but it seems like there is a different behavior when clicking and dragging somewhere. The first click moves the editing caret to that new location. Is it possible to add a setting where we can choose whether to move the caret to that location, or just move the viewing window?
[CodeGlance Pro-1.4.8-pre.zip](https://github.com/Nasller/CodeGlancePro/files/9278513/CodeGlance.Pro-1.4.8-pre.zip)
check on this,setting the jump behavior

**Comment by ryerrappa** [comment]
Thanks for the quick response! I will take a look and respond here once I do.
