### ISSUE TITLE
[建议]迷你地图视窗在地图的相对位置应该和编辑器视窗在编辑器上的相对位置一致

### ISSUE THREAD

**Issue by YiiGuxing** [Nasller/CodeGlancePro#38]
迷你地图和编辑器目前存在视窗的相对位置不一致的问题：
![img](https://user-images.githubusercontent.com/10737066/178435022-8e78cae8-f0d2-43e0-8398-b5bfa1a50903.png)

如果两者的相对大小与位置都一致的话，迷你地图是不是就能真实地反应了编辑器视窗与编辑器位置的相对关系呢？这样是不是就有更好的使用体验了呢？希望作者考虑一下这个建议。

VS Code 中两者的相对大小与位置就是一致的：
![image](https://user-images.githubusercontent.com/10737066/178436449-c6229d8a-cb32-4c80-b56d-169d11ce55f0.png)

**Comment by Nasller** [comment]
Duplicate of #5

**Comment by Nasller** [comment]
关于这个不好改，主要是jb的visualline在readmode 里就只有一行，按道理是不能显示的因为算是fold了

**Comment by Nasller** [comment]
> 在非 Reader Mode 下还是会出现相对位置不一致的问题：
> 
> ![image](https://user-images.githubusercontent.com/10737066/178439032-cb14189c-0a75-4d85-a3d4-ae8e6b1a5aba.png)

你看下是不是有inlayHint，那玩意儿也会影响

**Comment by Nasller** [comment]
实际上vscode里没有read mode那种大面积隐藏的操作，而inlayhit还稍微好弄点但是也会出现奇怪问题，inlayhit不算一行鼠标点击不到，vs中的做法是会出现视窗抖动，自动扩大视窗范围，我倒是试过，但是计算的非常头疼，滚动效果也会变。这两个问题目前我是没什么好方法解决了

**Comment by YiiGuxing** [comment]
没有，也没有代码折叠，就是代码行太多了7千行，位置在上面一点的看不出偏移来，越滑到下面偏移越大。

**Comment by YiiGuxing** [comment]
。。。我把inlayhit全关掉就好了。果然是inlayhit影响到了。。。

**Comment by YiiGuxing** [comment]
哈哈，希望有大佬能来优化一下这个问题吧，寻求大佬的帮助。只是我也没有更多的时间和精力了，自己的项目也是有一大堆计划堆积着呢，要不然我也可以尝试一下。。。

**Comment by Nasller** [comment]
Duplicate of #7

**Comment by Nasller** [comment]
[CodeGlance Pro-1.4.7.zip](https://github.com/Nasller/CodeGlancePro/files/9217017/CodeGlance.Pro-1.4.7.zip)
你好大佬，我在1.4.7中尝试修复了这个问题，请帮忙看看是否如预期，inlayhit不出意外后续应该也能实现，不过可能精度会有一丢丢问题

**Comment by YiiGuxing** [comment]
> [CodeGlance Pro-1.4.7.zip](https://github.com/Nasller/CodeGlancePro/files/9221015/CodeGlance.Pro-1.4.7.zip) 你好大佬，我在1.4.7中尝试修复了reader mode 和 inlay hits 问题，请帮忙看看是否如预期，不过可能精度会有一丢丢问题

牛逼！精度已经很高了，只不过在文件行数很大的时候误差会变得比较明显，不过已经很好了！
