### ISSUE TITLE
Incorrect minimap scrolling in .ipynb files

### ISSUE THREAD

**Issue by antonpavlovskyi** [Nasller/CodeGlancePro#39]
1. Which Glance version and IDEA version?
1.4.3 and Build #DS-221.5080.210, built on April 12, 2022
2. Do you enabled reader mode option?
no
3. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/73330579/178462955-3af4e102-d815-41f4-a2b1-16cb3018b486.png)
![image](https://user-images.githubusercontent.com/73330579/178463279-156ec5e4-5ed4-47d3-b502-1517574c888e.png)
4. What steps will reproduce the issue?
Create a .ipynb file and run some cells to get output.

**Comment by Nasller** [comment]
sorry,This seems to be because those words do not belong to the editor can cause this problem,and hard to fix.

**Comment by spas-minkov** [comment]
I have the same problem with .java files in IDEA. I found out that it is due to the "new functionality" of inlay hints.
![1 problem](https://user-images.githubusercontent.com/57368162/179792182-32b339ec-9b74-403d-9476-d63871e559c6.jpg)
![3 line gap](https://user-images.githubusercontent.com/57368162/179792230-3706eae7-428a-4990-bd17-dd3b7163523d.jpg)
![2 settings](https://user-images.githubusercontent.com/57368162/179792210-2d85ba50-c8ed-4d85-ab2e-8f9dd8acb1e3.jpg)

If the position of the hints is "Top" which is the default setting, they create "gaps" in the line numbering, which is not detected (detectable?) by "Code Glance".  Changing the position of the hints to "Right" (or disabling them completely) fixes the problem.

**Comment by Nasller** [comment]
> I have the same problem with .java files in IDEA. I found out that it is due to the "new functionality" of inlay hints.
> 
> ![1 problem](https://user-images.githubusercontent.com/57368162/179792182-32b339ec-9b74-403d-9476-d63871e559c6.jpg)
> 
> ![3 line gap](https://user-images.githubusercontent.com/57368162/179792230-3706eae7-428a-4990-bd17-dd3b7163523d.jpg)
> 
> ![2 settings](https://user-images.githubusercontent.com/57368162/179792210-2d85ba50-c8ed-4d85-ab2e-8f9dd8acb1e3.jpg)
> 
> 
> 
> If the position of the hints is "Top" which is the default setting, they create "gaps" in the line numbering, which is not detected (detectable?) by "Code Glance".  Changing the position of the hints to "Right" (or disabling them completely) fixes the problem.

please read #7. I can't fix this. I need someone to help me.

**Comment by glut410** [comment]
## this is the solution from VSCode
![issue](https://user-images.githubusercontent.com/46321515/180206140-b43682b4-d87a-4764-9749-6c7e96853eb2.png)

**Comment by glut410** [comment]
**maybe we can optimize the problem like this**
![solution](https://user-images.githubusercontent.com/46321515/180208498-a13ec562-ffde-468c-9051-be63eae7f5a6.png)

It connects the code and the minimap to help locate the code. Although not solving the underlying problem, this optimizes the problem.

**Comment by Nasller** [comment]
sorry,don't know what it mean

**Comment by Nasller** [comment]
> I have the same problem with .java files in IDEA. I found out that it is due to the "new functionality" of inlay hints. ![1 problem](https://user-images.githubusercontent.com/57368162/179792182-32b339ec-9b74-403d-9476-d63871e559c6.jpg) ![3 line gap](https://user-images.githubusercontent.com/57368162/179792230-3706eae7-428a-4990-bd17-dd3b7163523d.jpg) ![2 settings](https://user-images.githubusercontent.com/57368162/179792210-2d85ba50-c8ed-4d85-ab2e-8f9dd8acb1e3.jpg)
> 
> If the position of the hints is "Top" which is the default setting, they create "gaps" in the line numbering, which is not detected (detectable?) by "Code Glance". Changing the position of the hints to "Right" (or disabling them completely) fixes the problem.

[CodeGlance Pro-1.4.7.zip](https://github.com/Nasller/CodeGlancePro/files/9218542/CodeGlance.Pro-1.4.7.zip)

hello,this issuse now fixed,please check on this,but precision problem may occur
