### ISSUE TITLE
[BUG] The scrollbar and the mini-map scrollbar are not in the same position

### ISSUE THREAD

**Issue by Absolves** [Nasller/CodeGlancePro#4]
The position of the scrollbar on the mini-map is not the same as the position of the code. For example, if I pull the code to the bottom, the scrollbar of the mini-map is not at the bottom.

**Comment by Nasller** [comment]
can you show a picture?

**Comment by Absolves** [comment]
<img width="689" alt="1" src="https://user-images.githubusercontent.com/47398005/160972434-50da224c-2058-4fd8-9775-62a312d4e9a6.png">

**Comment by Nasller** [comment]
do you enabled reader mode option?

**Comment by Nasller** [comment]
Which glance did you choose?

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/160975085-bbb4e5ae-1011-4f3d-9620-4cc467ab97c9.png)
like this

**Comment by Absolves** [comment]
No, I didn't enable this mode. I am editing the code.

**Comment by Nasller** [comment]
I can't revert your problem.In my editor is not appear. please check your fold things，possible expand it

**Comment by Absolves** [comment]
Okay. It makes me confused, in fact, both CodeGlance2 and CodeGlance3 run fine on my Intellij idea. I don't know what the reason is. Thanks for your help.

**Comment by Nasller** [comment]
If you can please provide the text, and the corresponding Settings.i can try

**Comment by Nasller** [comment]
Is it normal to reopen the file？
