### ISSUE TITLE
[FEATURE] Show breakpoints

### ISSUE THREAD

**Issue by dydzio0614** [Nasller/CodeGlancePro#42]
I would like to be able to see breakpoints in scroll, taking full width - just like current line is selected in blue color

**Comment by Nasller** [comment]
[CodeGlance Pro-1.4.8-pre.zip](https://github.com/Nasller/CodeGlancePro/files/9286535/CodeGlance.Pro-1.4.8-pre.zip)
check on this,and please feedback

**Comment by dydzio0614** [comment]
![Preview](https://user-images.githubusercontent.com/9436577/183580584-c4213564-6c63-4dc0-ab00-0b2672c8eddc.png)

Works fairly well, but the space occupied by code is not highlighted

**Comment by Nasller** [comment]
Should be covered by the other errorStripes highlight color
