### ISSUE TITLE
[FEATURE-ENHENCEMENT] option to hide the eye in the top right of editors

### ISSUE THREAD

**Issue by zartc** [Nasller/CodeGlancePro#43]
Please could you provide an option to hide the eye icon displayed in the top right corner of editors ?

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/184093265-a860b84c-ea67-4eac-93a3-26a51a5e0bad.png)
check on this

**Comment by zartc** [comment]
wow! I was totally unaware of the exitance of this right-click menu. Thanks.
