### ISSUE TITLE
[FEATURE] Show only code without comments

### ISSUE THREAD

**Issue by gogainda** [Nasller/CodeGlancePro#44]
Is it possible to strip out comments from the minimap?

**Comment by Nasller** [comment]
whats like comments

**Comment by gogainda** [comment]
in particular JavaDocs

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/185632451-45c0f216-b08a-47d7-bffb-3bec3b402e5a.png)
but will have lot of blank area

**Comment by Nasller** [comment]
Sorry, after consideration, decide not to add this feature
