### ISSUE TITLE
[BUG] Lock bool does not lock scrollbar size

### ISSUE THREAD

**Issue by DevChrisTimmerman** [Nasller/CodeGlancePro#46]
1. Which Glance version and IDEA version?
 Code Glance Pro 1.5.0 & Rider 2022.2.2 Build #RD-222.3962.23

2. Could you show Glance config picture and minimap picture?
![config](https://user-images.githubusercontent.com/60178120/188157471-e6e1e442-6762-48ba-a652-0bd0c4e8706f.png)
![smallScroll](https://user-images.githubusercontent.com/60178120/188157892-3ab749cb-57de-4fea-a2a4-e62a897b6838.png)
Blackedout code my code for privacy reasons

3. What steps will reproduce the issue?
Open two windows in Rider and resize one window, which will resize the scroll bar

**Comment by Nasller** [comment]
sorry,this is a feature

**Comment by DevChrisTimmerman** [comment]
What, how? Whats the purpose of the lock bool then?

**Comment by Nasller** [comment]
Automatic calculation of width is mainly to take care of those with small screens. The purpose of locking the border is not to drag and drop to set the width.
![image](https://user-images.githubusercontent.com/26132153/188252062-da6fa61d-ca1d-4191-80f2-dea52335ea89.jpeg)

**Comment by DevChrisTimmerman** [comment]
Could I request a lock feature? Or atleast a minimum width that it doesn't go under?

**Comment by Nasller** [comment]
ok,i will provide a configuration that turns off automatic width calculation.check this.config in right click
[CodeGlance Pro-1.5.1.zip](https://github.com/Nasller/CodeGlancePro/files/9483050/CodeGlance.Pro-1.5.1.zip)

**Comment by DevChrisTimmerman** [comment]
I replaced the files you gave me with the files in my appdata but it still resizes

**Comment by Nasller** [comment]
are you install it and disable the config?
![image](https://user-images.githubusercontent.com/26132153/188401504-a7ab5a34-0552-42fe-910f-1df14665cb1f.png)

**Comment by DevChrisTimmerman** [comment]
Oh okay cool, I didn't see that setting, thank you dear sir!
