### ISSUE TITLE
Add viewport border, or increase unfocused viewport background color saturation

### ISSUE THREAD

**Issue by dominicpalmer** [Nasller/CodeGlancePro#48]
The viewport background colour has low saturation when unfocused. The saturation increases on hover, and increases further on click.

CodeGlance only allows one viewport colour to be set for all themes. So for people who use both light and dark themes (and switch regularly), it's hard to find a middle ground background colour that will keep the viewport clearly visible when it's unfocused.

Example with the viewport colour set to #01579B (blue), while using a light theme. Left to right is unfocused, focused and clicked:

![image](https://user-images.githubusercontent.com/32597988/191739993-fc8fd14d-f326-4060-8961-e866f9202336.png)

Although this blue is clearly visible when using a dark theme, it's hard to use with a light theme, particularly when unfocused.

Ideas:

1. Add a fixed border around the viewport, the colour of which can be set by the user by an option.
2. Add saturation slider options for the viewport background colour.

For example, Visual Studio's implementation of the minimap is lacking a viewport background colour, but is still usable because of well defined borders:

![image](https://user-images.githubusercontent.com/32597988/191740506-a0fe6650-b453-4181-a368-1bcc555eea78.png)

**Comment by Nasller** [comment]
OK, I will consider the option of the fixed border.

**Comment by Nasller** [comment]
Hi,try this setting viewport border thickness > 0 in config.
[CodeGlance Pro-1.5.2.zip](https://github.com/Nasller/CodeGlancePro/files/9628632/CodeGlance.Pro-1.5.2.zip)

**Comment by dominicpalmer** [comment]
Perfect! Thanks for the quick response. Will this make a release?

![image](https://user-images.githubusercontent.com/32597988/191857652-981974f0-a6c6-4912-ab55-aaf878552c8c.png)

**Comment by Nasller** [comment]
Yes,will release in the next week
