### ISSUE TITLE
Please Add a option to disable the feature -- "Quick view code on Glance"

### ISSUE THREAD

**Issue by feilix** [Nasller/CodeGlancePro#50]
I have two screens, A is for citrix where idea exists in it, B is for other.
The "Quick view code on Glance" will always dispaly in A when I move the mouse from A to B. So I need a option to disable it.
![图片](https://user-images.githubusercontent.com/55008613/196890759-bdd11ec8-4312-42aa-849f-c1d8a282e252.png)

**Comment by Nasller** [comment]
disable once or always?

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/196891511-e87a54b3-63ba-4b0d-954b-b8721e1e387c.png)
always close use this settings

**Comment by feilix** [comment]
> ![image](https://user-images.githubusercontent.com/26132153/196891511-e87a54b3-63ba-4b0d-954b-b8721e1e387c.png) always close use this settings

this works. Thanks
