### ISSUE TITLE
Disable hightlights

### ISSUE THREAD

**Issue by AndreKR** [Nasller/CodeGlancePro#51]
I'm currently using CodeGlance Pro 1.5.2 in CLion 2022.1.3.

When there is an inspection warning in the code the respective part in CodeGlance is highlightes yellow:

![image](https://user-images.githubusercontent.com/1188538/197448315-20a43d6c-5784-4e38-a1c4-86653eae92b6.png)

(I don't actually know what this whole yellow line means, but anyway.)

I use CodeGlance to navigate, by basically remembering what each particular part of the code *looks like* in CodeGlance. The highlights are quite distracting and make it difficult to see the shape of the code.

At first I thought the option "Customize Highlighting Level" in the context menu was what I'm looking for, but that disables the warnings in the whole IDE (i.e. editor and scrollbars), which is not what I want. I want to keep the warnings, I just don't want them to cause highlights in CodeGlance.

**Comment by Nasller** [comment]
[CodeGlance Pro-1.5.3.zip](https://github.com/Nasller/CodeGlancePro/files/9849039/CodeGlance.Pro-1.5.3.zip)
try this

**Comment by JParkinson1991** [comment]
@Nasller 
Can confirm highlighting of inspections can be disabled in PHPStorm 2022.2.3 using package version 1.5.3.

| Before  | After |
| - | - |
| <img width="166" alt="Screenshot 2022-10-24 at 11 58 34" src="https://user-images.githubusercontent.com/6921398/197511154-ffd9b3f1-d1e0-40d0-9d6c-4331aec20b23.png">  | <img width="170" alt="Screenshot 2022-10-24 at 11 55 04" src="https://user-images.githubusercontent.com/6921398/197510786-8d049d03-c031-42d7-a3e8-d36e0e922ae9.png">  |

Setting used was `Filter Markup Highlight`. It might be worth making these labels a bit clearer? Other might, but I didn't know what they meant and just unchecked them all until highlights disappeared. (Note VCS is self-explanatory)

**Comment by JParkinson1991** [comment]
I see, I didn't realise they came from the SDK, in that case I wouldn't recommend changing them. Maybe just include somewhere the 'including' like you've listed above.

Regardless, main thing is highlights can be turned on and off so thank you for getting that working!

**Comment by AndreKR** [comment]
I think the labels are ok, I tried out every setting anyway. But I don't have Filter Markup Highlight in the settings with the latest version available in the Plugins list. I don't know what to do with the zip.

**Comment by JParkinson1991** [comment]
@AndreKR download the zip, 'Install Plugin from Disk' in the IDE and select the downloaded zip.


<img width="810" alt="Screenshot 2022-10-24 at 15 46 33" src="https://user-images.githubusercontent.com/6921398/197555386-dc62d64a-3d7c-4469-a0f2-bfbfc100e214.png">

**Comment by Nasller** [comment]
happy hear that,Thanks

> I see, I didn't realise they came from the SDK, in that case I wouldn't recommend changing them. Maybe just include somewhere the 'including' like you've listed above.
> 
> Regardless, main thing is highlights can be turned on and off so thank you for getting that working!
