### ISSUE TITLE
Setting for scrollbar hover delay before minimap appears

### ISSUE THREAD

**Issue by ekhahniii** [Nasller/CodeGlancePro#52]
An option to specify a time delay (in milliseconds) before the minimap appears during scrollbar hover would be quite useful. A default of e.g. 100 ms could be a reasonable default.

Currently, every time the mouse passes over the scroll bar, the minimap appears. This can become immensely distracting, e.g. when the IDE is in the background.

Thank you for this wonderful plugin!

**Comment by Nasller** [comment]
If with delay, that means you will have to stay your mouse on the scrollbar 100 ms, then minimap will show

**Comment by ekhahniii** [comment]
Yes, exactly.

**Comment by Nasller** [comment]
try this
[CodeGlance Pro-1.5.4-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/9976962/CodeGlance.Pro-1.5.4-SNAPSHOT.zip)

**Comment by ekhahniii** [comment]
It works excellently—thanks for your responsiveness! A delay of 10 ms seems to work well for me so far.

**Comment by Nasller** [comment]
okay
