### ISSUE TITLE
[Feature request] Markers/Labels

### ISSUE THREAD

**Issue by dev-null-undefined** [Nasller/CodeGlancePro#54]
Markers on the minimap,
Just like in Xcode 11 https://medium.com/@mumtaz.hussain/xcode-11-now-makes-mark-comments-a-lot-more-useful-with-minimap-feature-f8c658b293f
![image](https://user-images.githubusercontent.com/50732964/202877299-5eb10bda-bda1-47ff-92fe-e9d3f85063cf.png)

**Comment by Nasller** [comment]
sorry,not easy to add this

**Comment by dev-null-undefined** [comment]
> sorry,not easy to add this

Agreed but it would really awesome

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/202881337-d6d0d550-5533-4479-9242-f63f57902843.png)
i found that will overwrite
![image](https://user-images.githubusercontent.com/26132153/202881352-62ed0c5d-5a50-463a-8f25-116483799ea6.png)
this line.
If the implementation method is to cover the following lines with this tag, maybe can done

**Comment by Nasller** [comment]
Because the calculation rule of scrollbar scrolling is related to the length of this document

**Comment by dev-null-undefined** [comment]
But overwriting parts of the minimap after the mark or before if at the end of the file, should be fine.
And I don't think there is any thing like that on the market right now even tho this feature seems really useful.

Also it could be very nice to have that on hover functionality https://fredriccliver.medium.com/using-a-quick-list-on-the-minimap-in-xcode-760d678e4847
Or add that as while holding certain keyboard shortcut that could work as well.
![image](https://user-images.githubusercontent.com/50732964/202886021-41844fad-03f5-4460-aa71-b518a5222bb4.png)

**Comment by dev-null-undefined** [comment]
That should be easier to implement but the Marks in my humble opinion look better and are more useful.

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/202886541-5af7e143-7c3c-472e-ab09-076a47ac16b1.png)
if this line has highlight will render like this
just like
![image](https://user-images.githubusercontent.com/26132153/202886579-7ffa3a91-6214-4a74-99d2-7201819257bb.png)

**Comment by Nasller** [comment]
I have completed the preliminary implementation of the mark label(in branch mark_label), but I have encountered some problems. If you have time, can you help me

**Comment by dev-null-undefined** [comment]
> I have completed the preliminary implementation of the mark label(in branch mark_label), but I have encountered some problems. If you have time, can you help me

Would love to do you have any other way of communication? Maybe discord or something?
Communicating using GitHub issue seems wrong :D and also kind of slow.

**Comment by Nasller** [comment]
tg？

**Comment by Nasller** [comment]
[CodeGlance Pro-1.5.5-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10096006/CodeGlance.Pro-1.5.5-SNAPSHOT.zip)
give it some test

**Comment by cloudlier** [comment]
Hello, did this ever get implemented?

If so is there any documentation on how to create markers?

Thanks

**Comment by Nasller** [comment]
Yes,just type //MARK: - Test

**Comment by cloudlier** [comment]
I see, would you have plans to implement this for `.py` files in Pycharm as well?

**Comment by Nasller** [comment]
should be applicable most of comments

**Comment by cloudlier** [comment]
It does indeed, thank you!
