### ISSUE TITLE
[BUG] Choice for `Show Minimap on scrollbar hover` is forgotten between IDE sessions

### ISSUE THREAD

**Issue by ekhahniii** [Nasller/CodeGlancePro#56]
When the IDE is restarted, the minimap forgets the selection (in the context menu of the minimap) for "show minimap on scrollbar hover".

1. Which Glance version and IDEA version?

PyCharm: 2022.2.3
CodeGlancePro: 1.5.4

2. Could you show Glance config picture and minimap picture?

n/a

3. What steps will reproduce the issue?

- Load a project
- Enable `Show Minimap on scrollbar hover` in the minimap context menu
- `File` > `Invalidate Caches` > `Just restart`
- Observe `Show Minimap on scrollbar hover` is disabled

**Comment by Nasller** [comment]
[CodeGlance Pro-1.5.5-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10099865/CodeGlance.Pro-1.5.5-SNAPSHOT.zip)
try this

**Comment by ekhahniii** [comment]
@Nasller Thanks for the quick fixes! Indeed, both #56 and #57 seem to be addressed.

**Comment by Nasller** [comment]
okay
