### ISSUE TITLE
[BUG] Wrong range in reference com.intellij.microservices.url.parameters.QueryParameterNameReference(JSLiteralExpression:(24,32)): (24,32). Reference text: ''''

### ISSUE THREAD

**Issue by xiaofei3062** [Nasller/CodeGlancePro#58]
1. Which Glance version and IDEA version?
webstorm 2022.3
2. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/51069900/205525174-251cf480-e32b-4a1f-8807-83cd06cfa8d8.png)
3. What steps will reproduce the issue?
format, or unknown step

**Comment by Nasller** [comment]
[CodeGlance Pro-1.5.6-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10150045/CodeGlance.Pro-1.5.6-SNAPSHOT.zip)
try this

**Comment by xiaofei3062** [comment]
> [CodeGlance Pro-1.5.6-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10150045/CodeGlance.Pro-1.5.6-SNAPSHOT.zip) try this

no problem
