### ISSUE TITLE
[BUG] Wrong range in reference com.intellij.microservices.url.parameters.QueryParameterNameReference(JSLiteralExpression:(24,32)): (24,32). Reference text: ''''

### ISSUE THREAD

**Issue by xiaofei3062** [Nasller/CodeGlancePro#60]
1. Which Glance version and IDEA version?
webstorm 2022.3
2. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/51069900/206382117-5a593b7d-aadb-44b4-bd9c-b55992f856dd.png)
3. What steps will reproduce the issue?
Did nothing, reopened the project, and scrolled back and forth a few times

**Comment by Nasller** [comment]
忽略这个，sdk打印的报错
