### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by clearskystudio** [Nasller/CodeGlancePro#65]
1. Which Glance version and IDEA version?
1.5.7 Rider 2022.3

3. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/37312570/207894869-06a1aed5-81e1-41f4-aff6-c35119a3813c.png)

5. What steps will reproduce the issue?
Throws an error for **line** comment
//MARK: - tag1
Works ok for **block** comment
/*MARK: - tag2
*/

**Comment by Nasller** [comment]
ok,will be fixed tomorrow

**Comment by Nasller** [comment]
try this 
[CodeGlance Pro-1.5.8-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10239256/CodeGlance.Pro-1.5.8-SNAPSHOT.zip)

**Comment by clearskystudio** [comment]
it worked, thanks!
