### ISSUE TITLE
Please add option to click anywhere on the code glance canvas to move there directly

### ISSUE THREAD

**Issue by Jarrodsz** [Nasller/CodeGlancePro#66]
Please add option to click anywhere on the code glance canvas to move there directly
Like clicking halfway on the glance canvas should switch the IDE to halfway the code in the IDE.

**Comment by Nasller** [comment]
does't know what it mean

**Comment by Nasller** [comment]
as i know, it will jump to the actual location of your code.

**Comment by Nasller** [comment]
Try this one, this is you want? (set click type to mouse position)
[CodeGlance Pro-1.5.9-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10277073/CodeGlance.Pro-1.5.9-SNAPSHOT.zip)
