### ISSUE TITLE
stealing focus?

### ISSUE THREAD

**Issue by jerry1970** [Nasller/CodeGlancePro#67]
I have not been able to determine it with certainty yet, but I am getting the idea that the CodeGlance plugin steals focus when opening PHPStorm or even a document. Could that be true? Any thoughts on this?

**Comment by Nasller** [comment]
what is the stealing focus mean?

**Comment by jerry1970** [comment]
Oh sorry, I mean I open PHPStorm, then go to another window (browser, file manager, whatever), and PHPStorm is brought back into focus, hiding what I was doing in the other window and even taking keyboard entries. It sometimes happens too when I open a file and switch to another program. Sometimes the IDE is so busy (indexing etc.) it just takes a while.

**Comment by Nasller** [comment]
CodeGlance will not stealing focus.and i use idea,didn't meet this situation
