### ISSUE TITLE
[BUG] Minimap and scrollbar isn't visible in markdown files when in "Preview" mode

### ISSUE THREAD

**Issue by ChristopherHaws** [Nasller/CodeGlancePro#68]
1. Which Glance version and IDEA version?
Rider 2022.3.1 and IntelliJ 2022.3.1

2. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/5934505/212523782-cfd3fb89-487d-4e8c-bba1-b25ddd73c1bb.png)
![image](https://user-images.githubusercontent.com/5934505/212523668-3ab54e33-9483-4ad3-aa30-29f9e4433fad.png)

3. What steps will reproduce the issue?
- Open a markdown file
- Go to "Preview" mod
- Notice that there is no scrollbar or minimap

NOTE: I am using the beta "New UI" in the IDE. I'm not sure if that is the cause or not.

**Comment by Nasller** [comment]
sorry,it is not available in preview mode. it can only be used in the editor.

**Comment by ChristopherHaws** [comment]
Sorry, what I mean is that I have the original scroll bar disabled in your plugin and it doesn't re-enable it when in the markdown preview so there is no scrollbar visible.

**Comment by Nasller** [comment]
All settings only apply to the editor.

**Comment by ChristopherHaws** [comment]
Yes, that's correct.

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/214812223-3d0354b4-a584-4598-a363-6d768faa61fc.png)
Not find the problem

**Comment by Nasller** [comment]
As far as I know in IDEA 2023.1 EAP exist the problem seems to have nothing to do with the plugin, close the hide original scrollbar options still won't appear

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/214834038-ba6a28a3-667e-4907-83dc-1e60bfd0fa5b.png)
![image](https://user-images.githubusercontent.com/26132153/214834065-61a563e3-8495-48a9-a8d9-c71b8f68b6cb.png)

**Comment by Nasller** [comment]
Perhaps this is the official behavior
