### ISSUE TITLE
[BUG] LOG file type has incorrect lines

### ISSUE THREAD

**Issue by kotofos** [Nasller/CodeGlancePro#69]
1. Which Glance version and IDEA version?
1.5.9
PyCharm 2022.3.1 Build #PY-223.8214.51, built on December 20, 2022

2. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/2912647/213204758-1c0974bd-2c60-4405-a3b6-dd6615d9a548.png)

![image](https://user-images.githubusercontent.com/2912647/213203578-2253a491-bd00-4b10-bafe-9eb6cdfb02e1.png)

3. What steps will reproduce the issue?
Open a .log file (pytest log file in my case)
It must be detected as log file type by pycharm. Plain text is ok.
[test.log](https://github.com/Nasller/CodeGlancePro/files/10447567/test.log)

4. Expected
When file is text type then it looks ok
![image](https://user-images.githubusercontent.com/2912647/213204317-0aa1a23d-96e4-4201-92ab-7a2f82143bbd.png)

**Comment by Nasller** [comment]
look likes soft wrap error

**Comment by kotofos** [comment]
The soft wrap was disabled.
Enabling and disabling soft wrap does not fix it. Minimap looks slightly different when the soft wrap is enabled for log files.
Enabling soft wrap on text-type files works ok.

**Comment by Nasller** [comment]
i see,let me debug this

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/213219507-7cac071e-abdd-4c1c-9fee-e3d3e1a10525.png)
which type is you selected?

**Comment by Nasller** [comment]
i download ideolog jetbrains plugin.and it see ok
![image](https://user-images.githubusercontent.com/26132153/213227799-1dd68f5e-5bfc-4639-a355-2189b3943c34.png)

**Comment by Nasller** [comment]
i know.This is the ideolog plugin bugs. because the <code>LogHighlightingIterator</code> doesnt give me the \n text

**Comment by Nasller** [comment]
[CodeGlance Pro-1.6.0-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10448975/CodeGlance.Pro-1.6.0-SNAPSHOT.zip)
try this

**Comment by kotofos** [comment]
This worked, thx.
Now it looks like this:
![image](https://user-images.githubusercontent.com/2912647/213259806-8adccdbe-47ff-4b2a-9c7f-10c28e1f5d22.png)
Is it suppose to have green background? It is green only for log files.

**Comment by kotofos** [comment]
Ah, got it. It is coming from the IDE itself, b/c scrollbar is green too.

**Comment by Nasller** [comment]
> Ah, got it. It is coming from the IDE itself, b/c scrollbar is green too.

yes,this green error line comes from idealog, and there is a configuration to control its switch, from Advanced error stripe (heat map)

**Comment by kotofos** [comment]
Ok, thx, this can be closed.
