### ISSUE TITLE
Plugin doesn't work with EAP 2023.1

### ISSUE THREAD

**Issue by maicol07** [Nasller/CodeGlancePro#70]
Hi,
the plugin is marked as incompatible with the new 2023.1 EAP. Can you add support for it?
Thanks

**Comment by Nasller** [comment]
use this  [CodeGlance Pro-1.6.0-2023.1-signed.zip](https://github.com/Nasller/CodeGlancePro/files/10509274/CodeGlance.Pro-1.6.0-2023.1-signed.zip)
plugin already upload to approve

**Comment by maicol07** [comment]
I've tried the new version, but it seems the CodeGlance scrollbar doesn't appear

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/215059577-3c722344-7e08-44ce-817e-26baffc8cf7e.png)

**Comment by Nasller** [comment]
[CodeGlance Pro-1.6.0-2023.1-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/10517997/CodeGlance.Pro-1.6.0-2023.1-SNAPSHOT.zip)
try this

**Comment by Nasller** [comment]
ok,thx
