### ISSUE TITLE
[IMPROVEMENT] Drag minimap window without navigate to it 

### ISSUE THREAD

**Issue by renebaeu** [Nasller/CodeGlancePro#72]
First of all. Amazing Plugin!!!

I have an Idea, but don*t know if it is even possible to implement. 

By now, we have to navigate the mouse to the minimap and then drag the minimap window to the position where we want go. 

I would love to just press the middle mouse button or a mouse key combination to drag the minimap window to the position i like. Without first navigate the mouse to the minimap window.   

I know, there are plugins like "Fast Mouse Scrolling", but that is differently. Fast Mouse Scrolling scrolls a delta to the mouse movement, it is always relatively. Clicking the minimap window and drag it, is direct. If I want to go to a method for example, i just drag the minimap window to that position. I love it.  

Best regards,

René

**Comment by Nasller** [comment]
If you want to implement it, you must have a window that can listen to mouse events
I think it should be the editor.
I don't know how to get the mouse position after pressing the shortcut key in editor
