### ISSUE TITLE
[BUG] CodeGlancePro is Visible as a Small Vertical Bar in PyCharm Python Console

### ISSUE THREAD

**Issue by blackadar** [Nasller/CodeGlancePro#73]
1. Which Glance version and IDEA version?

CodeGlancePro 1.6.0-2023.1

2. Could you show Glance config picture and minimap picture?

![image](https://user-images.githubusercontent.com/20449792/225990930-6e195c11-83a7-4011-8cef-d9c8f36d05c3.png)

![image](https://user-images.githubusercontent.com/20449792/225991057-bddfe1c8-9055-4cde-a371-f90b53b02887.png)

3. What steps will reproduce the issue?

Open Python Console in PyCharm and move the cursor around the text input area. A minimap will appear as a thin vertical bar to the right of the input marker.

**Comment by Nasller** [comment]
Wait until PyCharm 2023.1 is released to see this issue

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/229006867-982d3d41-4551-446f-ac79-b58e7d63a8cf.png)
It should be an official issue
