### ISSUE TITLE
[BUG] Identifier under caret is not showing as full line highlight

### ISSUE THREAD

**Issue by clearskystudio** [Nasller/CodeGlancePro#74]
1. Which Glance version and IDEA version?
1.6.1 and 2023.1

2. Could you show Glance config picture and minimap picture?
![image](https://user-images.githubusercontent.com/37312570/233956562-82ec20be-5d4b-4983-8cd6-d42824b9606f.png)

3. What steps will reproduce the issue?
Enable "Show full line highlight" from the right-click menu.
Set the caret to an identifier, look for a full line highlight in the Minimap.

**Comment by Nasller** [comment]
Because it needs to be distinguished from error stripes, the identifier under the insertion symbol will not display the entire line

**Comment by Nasller** [comment]
In fact, this setting is used for error stripes

**Comment by clearskystudio** [comment]
It's not a bug then, more of an improvement I guess 😅
I use color coding to differentiate errors, warnings, suggestions, etc.
But actually the most frequently, at least in my case, I use the minimap to look for under caret identifiers since it's such a time saver.  And it would be noticeably easier to look through the map for a line rather than a couple of pixels.

**Comment by Nasller** [comment]
try this

**Comment by clearskystudio** [comment]
It's working. Thanks so much for your work!

**Comment by Nasller** [comment]
thank you for your feedback
