### ISSUE TITLE
[BUG] 2023.2 EAP

### ISSUE THREAD

**Issue by Drenalol** [Nasller/CodeGlancePro#76]
JetBrains Rider 2023.2 EAP is started, please update it.
![image](https://github.com/Nasller/CodeGlancePro/assets/4239087/e064e7b9-44ae-4cc3-a4d7-14d5093b4328)

**Comment by Nasller** [comment]
[CodeGlance Pro-1.6.3-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/11483623/CodeGlance.Pro-1.6.3-SNAPSHOT.zip)
try this

**Comment by Drenalol** [comment]
Thanks, worked.

**Comment by Nasller** [comment]
ok,will be published later
