### ISSUE TITLE
[BUG] Problem with scrollbars

### ISSUE THREAD

**Issue by MohammadMD1383** [Nasller/CodeGlancePro#77]
1. Which Glance version and IDEA version?
**JetBrains Rider 2023.2 EAP 2 - 1.6.3**

2. Could you show Glance config picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/69088224/6e2e8857-8a4f-488e-839e-ca506738db08)
![image](https://github.com/Nasller/CodeGlancePro/assets/69088224/cf833b6f-cb20-4920-a36f-c1b89edddfdf)

3. What steps will reproduce the issue?

after changing theme, after a period of time the scrollbars are like what you see in the picture (thumb is not recognizable)

going to `Settings > Editor > Color Scheme` and resetting the theme will fix the issue temporarily.

**Comment by Nasller** [comment]
What does it mean(thumb is not recognizable)?

**Comment by MohammadMD1383** [comment]
sorry for poor English ...

this is the problem
![image](https://github.com/Nasller/CodeGlancePro/assets/69088224/90da9d0c-8195-4c0e-ae69-21028df26e18)


and this is the correct behavior (after resetting Editor Color Scheme):
![image](https://github.com/Nasller/CodeGlancePro/assets/69088224/65d0c0de-2a04-4685-ad83-3ca627cf3df9)

**Comment by Nasller** [comment]
It doesn't look like it's caused by this plugin. As far as I know, the horizontal scroll bar is not used in the code. You can try to disable this plugin to see if it is caused by this plugin.

**Comment by MohammadMD1383** [comment]
yes you're right!

after disabling the plugin the problem still persists
