### ISSUE TITLE
[BUG]split and move后，将拆分的文件拖到一个新的窗口，不会显示缩略图

### ISSUE THREAD

**Issue by Kumome** [Nasller/CodeGlancePro#78]
1. Which Glance version and IDEA version?
1.6.0
2. Could you show Glance config picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/51330926/e1f9621c-e592-442a-86f2-4c6ff806fd3c)
3. What steps will reproduce the issue?
RT

**Comment by Kumome** [comment]
> 啥操作， ![image](https://user-images.githubusercontent.com/26132153/241705469-ddaec8b4-4bb9-49db-ab3f-e93cbee9e17a.png) 这个？

右键菜单->split and move right
或者默认的快捷键是 alt + 双击(鼠标左键)
![image](https://github.com/Nasller/CodeGlancePro/assets/51330926/a2142a77-bdd5-42d4-8cb0-808b63cb2f33)
![image](https://github.com/Nasller/CodeGlancePro/assets/51330926/fcdd70e4-9381-4b10-8ace-faa5fdaa6647)

**Comment by Kumome** [comment]
> 啥操作， ![image](https://user-images.githubusercontent.com/26132153/241705469-ddaec8b4-4bb9-49db-ab3f-e93cbee9e17a.png) 这个？

哦哦，同时打开多个文件的时候才有这个选项，直接点这个也一样

**Comment by Nasller** [comment]
1.6.0?升到最新看看，我直接点那个打开新窗口后有缩略图诶

**Comment by Kumome** [comment]
> 1.6.0?升到最新看看，我直接点那个打开新窗口后有缩略图诶

是1.6.0，可能是pycharm版本的问题，在另一台电脑上是正常的(PyCharm 2023.1 (Community Edition))。。
PyCharm 2022.2.3 (Professional Edition)上有问题
应该不会是设置的问题吧

**Comment by Kumome** [comment]
> 按道理应该是没啥问题的升个级看看

pycharm更新后还是稍微有点问题
首先上面的快捷键失效了(alt + 双击，配置显示还在)
重新设置后发现可能是鼠标快捷键的问题，给split right配置鼠标快捷键后，shift + F4在新开的窗口中使用鼠标快捷键split有概率没有缩略图(直接使用鼠标快捷键split偶尔也没缩略图)
之前正常的电脑上也能复现了，alt+双击默认是其它功能的快捷键，之前右键菜单点的没问题

话说这有可能是pycharm的bug了

**Comment by Nasller** [comment]
按你的操作在pycharm上试了试，先分离窗口然后shift+f4按烂了，没有出现没显示小地图的情况

**Comment by Kumome** [comment]
> 

先给split right配置一个鼠标快捷键，比如alt+右键双击，然后shift+f4分离窗口，在分离的窗口上alt+右键双击

**Comment by Kumome** [comment]
> 按你的操作在pycharm上试了试，先分离窗口然后shift+f4按烂了，没有出现没显示小地图的情况

实在不能复现就算了，不用鼠标快捷键了

**Comment by Nasller** [comment]
可以，我也重现了，回头看看

**Comment by Kumome** [comment]
> 可以，我也重现了，回头看看

大佬辛苦了

**Comment by Kumome** [comment]
> [CodeGlance Pro-1.6.4-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/11598370/CodeGlance.Pro-1.6.4-SNAPSHOT.zip) 试试这个

试了很多次都没出问题了，感谢大佬
