### ISSUE TITLE
[IMPROVEMENT] Add support for //region and #region

### ISSUE THREAD

**Issue by aronbudinszky** [Nasller/CodeGlancePro#79]
CodeGlancePro already supports highlighting `MARK` style comments to differentiate sections in the code:

```
// MARK: - Something! 
// ...will show up as a green highlighted text in the minimap
```

But `region` comments used in Java and Kotlin are not supported:

```
#region Something!
// Java code
#endregion
```

```
// region Something!
// Kotlin code
// endregion
```

Possible improvement would be to add support for these two section-marking syntaxes, making it work exactly like the current MARK feature.

**Comment by Nasller** [comment]
`region` start?

**Comment by Nasller** [comment]
I have an idea to make this expression a configuration item

**Comment by Nasller** [comment]
[CodeGlance Pro-1.6.5-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/11711393/CodeGlance.Pro-1.6.5-SNAPSHOT.zip)
try this

**Comment by aronbudinszky** [comment]
Thx for the fast response!

I installed the one above, but it did not work with Kotlin and `// region Region Name`. Do I have to set something up additionally?

**Comment by Nasller** [comment]
yes,you need set the config `Markers regex` to support `region` start

**Comment by aronbudinszky** [comment]
Yup, just had a look at the code changes and figured it out. But again you are too fast. :)

Works perfectly! Thanks for the amazing plugin.

**Comment by synthc** [comment]
> yes,you need set the config `Markers regex` to support `region` start

I'm having trouble getting this to work with `#region`.  I tried modifying the `Markers regex`, but I can't get it to do anything.  Does it only work on comments?

I would like to replicate the code map #region behavior in VS Code.

**Comment by Nasller** [comment]
> > yes,you need set the config `Markers regex` to support `region` start
> 
> 
> 
> I'm having trouble getting this to work with `#region`.  I tried modifying the `Markers regex`, but I can't get it to do anything.  Does it only work on comments?
> 
> 
> 
> I would like to replicate the code map #region behavior in VS Code.

yes, only work on comments

**Comment by synthc** [comment]
I see, thanks.

**Comment by CAZ-H** [comment]
Hey! Love this plugin, but can we reopen this? The use-case of #region in C# has not been satisfied and using comments in addition to #region is messy for other developers on the same project who aren't using this plugin. Ideally this feature should not be hardcoded to comments only; the comment prefix should instead be moved into the regex if this doesn't pose any performance issues (potentially with per-language configuration).

**Comment by Nasller** [comment]
The #region in C# is supposed to be a special syntax that doesn't apply to comments, so additional code may be required for compatibility with this

**Comment by Nasller** [comment]
i have support C# #region mark. everyone can test on it ? https://plugins.jetbrains.com/plugin/18824-codeglance-pro/edit/versions/eap

**Comment by CAZ-H** [comment]
It looks like it works! Thank you for your fast turnaround on this, this will be a huge efficiency gain for me!

**Comment by synthc** [comment]
This is working for me as well, thanks.
