### ISSUE TITLE
[BUG] Lines are not positioned correctly in the minimap

### ISSUE THREAD

**Issue by chris54721** [Nasller/CodeGlancePro#8]
Hi, thanks for maintaining this plugin!
I am experiencing a bug with how the lines are drawn in the minimap, as you can see in the picture below they are not in the correct position relative to the viewport. However all other elements of the minimap (git changes, current line etc) seem to be positioned correctly.

1. Which Glance version and IDEA version?
Glance 1.2.5, IDEA 2021.3.3.

2. Do you enabled reader mode option?
No

3. Could you show Glance config picture and minimap picture?
<img width="590" alt="image" src="https://user-images.githubusercontent.com/3685659/162229324-8ce8b522-5aa4-45fe-824c-af78b17a3b47.png">
<img width="933" alt="image" src="https://user-images.githubusercontent.com/3685659/162229525-76669572-0890-40f6-8917-90f8bb38fdaf.png">

(I made the viewport blue so it is easier to see)

4. What steps will reproduce the issue?
Open any file, the lines are placed incorrectly relative to the rest of the minimap.

**Comment by Nasller** [comment]
Do you modify the file  after modifying settings?1.2.5 version config have a problem.try to  reopened the file,then modify
in my editor positioned correctly
![image](https://user-images.githubusercontent.com/26132153/162346134-e0e7f01a-33fa-4993-9d32-305d001c432b.png)

**Comment by Nasller** [comment]
the config error will fix in the 1.2.6 version

**Comment by chris54721** [comment]
Same problem unfortunately with 1.2.6. (tried restarting / closing all files / updating config)

**Comment by Nasller** [comment]
emmm....can not reproduce the issue

**Comment by Nasller** [comment]
![image](https://user-images.githubusercontent.com/26132153/162419660-c94efe63-5f3f-47c5-b724-099e48ce3f59.png)
you problem seem like minimap not update or something else

**Comment by chris54721** [comment]
I tried to set pixels per line to 4 and it seems like the lines are rendered at 2x height compared to everything else. see for example the caret position here

<img width="197" alt="image" src="https://user-images.githubusercontent.com/3685659/162419899-2db3a9f6-6005-4fe0-ba7d-46ae58e42946.png">

**Comment by Nasller** [comment]
are your system is macOS

**Comment by chris54721** [comment]
Yes

**Comment by Nasller** [comment]
Sorry, I have no Macos's machine that can debug, i will think about it

**Comment by chris54721** [comment]
Okay, no problem, thank you.

Could it be related to the lines being drawn with WritableRaster while everything else uses Graphics2D? maybe they have different behaviors for scaling?

**Comment by Nasller** [comment]
can you try version before 1.2.2 and select config oldGlance true ,then see the minimap?

**Comment by Nasller** [comment]
[CodeGlance Pro-1.2.7.zip](https://github.com/Nasller/CodeGlancePro/files/8451910/CodeGlance.Pro-1.2.7.zip)
Can you give it a try？

**Comment by chris54721** [comment]
Tried both but no change unfortunately.

**Comment by Nasller** [comment]
Can you have used Codeglance before, can you display properly?

**Comment by chris54721** [comment]
CodeGlance 3 renders correctly for me (though it has other issues). Lines are rendered smaller than CodeGlancePro
<img width="141" alt="image" src="https://user-images.githubusercontent.com/3685659/162473912-f1dfbd01-da03-424b-b7c8-b60d4afbde73.png">

**Comment by Nasller** [comment]
In fact, the code between me and him is not very different. I will compare minimap

**Comment by chris54721** [comment]
I tried comparing the two plugins and applied the following patch and it seems to work:
```diff
===================================================================
diff --git a/src/main/kotlin/com/nasller/codeglance/panel/AbstractGlancePanel.kt b/src/main/kotlin/com/nasller/codeglance/panel/AbstractGlancePanel.kt
--- a/src/main/kotlin/com/nasller/codeglance/panel/AbstractGlancePanel.kt	(revision be5cc1f86140874057af2bf774697771c751504f)
+++ b/src/main/kotlin/com/nasller/codeglance/panel/AbstractGlancePanel.kt	(date 1649432595133)
@@ -197,7 +197,7 @@
         }
         val img = getDrawImage() ?: return
         if (buf == null || buf?.width!! < width || buf?.height!! < height) {
-            buf = ImageUtil.createImage(width, height, BufferedImage.TYPE_4BYTE_ABGR)
+            buf = BufferedImage(width, height, BufferedImage.TYPE_4BYTE_ABGR)
         }
         val g = buf!!.createGraphics()
         g.composite = AlphaComposite.getInstance(AlphaComposite.CLEAR)
Index: src/main/kotlin/com/nasller/codeglance/render/Minimap.kt
<+>UTF-8
===================================================================
diff --git a/src/main/kotlin/com/nasller/codeglance/render/Minimap.kt b/src/main/kotlin/com/nasller/codeglance/render/Minimap.kt
--- a/src/main/kotlin/com/nasller/codeglance/render/Minimap.kt	(revision be5cc1f86140874057af2bf774697771c751504f)
+++ b/src/main/kotlin/com/nasller/codeglance/render/Minimap.kt	(date 1649432402818)
@@ -27,7 +27,7 @@
 			if (img != null) img!!.flush()
 			// Create an image that is a bit bigger then the one we need, so we don't need to re-create it again soon.
 			// Documents can get big, so rather than relative sizes lets just add a fixed amount on.
-			img = ImageUtil.createImage(config.width, scrollState.documentHeight + (100 * config.pixelsPerLine), BufferedImage.TYPE_4BYTE_ABGR)
+			img = BufferedImage(config.width, scrollState.documentHeight + (100 * config.pixelsPerLine), BufferedImage.TYPE_4BYTE_ABGR)
 		}
 
 		val g = img!!.createGraphics()
```

I think it is more of a workaround since it is recommended not to use `BufferedImage`. Here is the built plugin, if it works for you I can submit a PR.
[CodeGlance Pro-1.2.7.zip](https://github.com/Nasller/CodeGlancePro/files/8453504/CodeGlance.Pro-1.2.7.zip)

**Comment by Nasller** [comment]
I have also suspected this place, so I deleted some in the previous submission. This method also creates BufferedImage by default.If it is useful to you, you can submit

**Comment by Nasller** [comment]
This place has not been changed in the first place. The purpose of changing this method is to try hidpi, but it seems to be useless.
