### ISSUE TITLE
可以让整行高亮的背景色与文字缩略块对齐吗？

### ISSUE THREAD

**Issue by imzxj** [Nasller/CodeGlancePro#82]
有点强迫症，上边有缝隙，可否能让文字块在行背景中居中，或者减小背景色的高度使与文字块一致

<img width="117" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/24448924/4fa91b07-927d-4267-a381-46369f418273">
<img width="134" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/24448924/1e0dd667-70fe-4a07-982c-95d3d66b7ac3">
<img width="131" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/24448924/d2cc8bd7-45eb-42b9-8fca-7c3e31733e3d">

**Comment by Nasller** [comment]
这本身就是两个一个填充的矩形，一个是写像素点，所以有缝隙是正常的
