### ISSUE TITLE
[Enhancement] Request support for scrollbar widening feature in Interllij IDEA Markdown preview mode.

### ISSUE THREAD

**Issue by zhouxinghong** [Nasller/CodeGlancePro#84]
[Enhancement] Request support for scrollbar widening feature in Interllij IDEA Markdown preview mode.

Because the screen scroll bar is very thin in Markdown preview mode, if your screen is larger, the scroll bar in Interllij IDEA Markdown preview mode will be displayed thinner, so the function of widening the scroll bar is needed. Hope you can take it and make it happen. Thanks again for the excellent Interllij Platform Extensions.

Screenshot of preview mode:
![image](https://github.com/Nasller/CodeGlancePro/assets/54253524/4f1541d8-fb81-4870-ab6c-a2197cbe818f)

OS: Windows10
Interllij IDEA: 2023.1.4
Version: 1.6.7

Question 2: 
Move hide and show buttons to the right mouse button menu.
It is recommended to move the hide and show buttons to the right-click menu of the mouse, so that the layout of the editor will look more reasonable and beautiful. I hope you can consider and adopt it.

screenshot:
![image](https://github.com/Nasller/CodeGlancePro/assets/54253524/ffa13eb3-2f54-4551-87c0-212fab2e94cf)

Improved Design:
![image](https://github.com/Nasller/CodeGlancePro/assets/54253524/0762a613-674f-40d3-9f2f-db36a532251e)

OS: Windows10
Interllij IDEA: 2023.1.4
Version: 1.6.7

**Comment by Nasller** [comment]
Question 1
Preview mode editor are not an editor implementation.so minimap can't be display in preview model
Question 2
actually you can use the shortcut key to disable the minimap,if you don't like the quick button

**Comment by zhouxinghong** [comment]
Question 1
Preview mode editor are not an editor implementation.so minimap can't be display in preview model
thank you for your reply! If the small map cannot be displayed, can the scroll bar be widened and enlarged?

**Comment by Nasller** [comment]
first,it may can be implement,but i think it should not be implement in this plugin

**Comment by zhouxinghong** [comment]
So could you please create a sister extension to achieve this? At present, the function of widening and zooming in on the scroll bar is realized. If the small map with scroll bar is implemented later when the technology is mature, do you think this is ok? 😜

**Comment by Nasller** [comment]
sorry, I don't have time to implement this. If you need it, I can provide you with some ideas to implement it

**Comment by zhouxinghong** [comment]
OK! I will contact you when I have installed the environment next time! Thanks! 😜
