### ISSUE TITLE
Option to hide "Hide minimap" button

### ISSUE THREAD

**Issue by G-Rath** [Nasller/CodeGlancePro#85]
I've just switched from CodeGlance3 and this plugin seems really well put together, so thank you - however I couldn't see an option to disable the "Hide minimap" button:

<img width="256" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/3151613/8710375d-535e-47e8-9d99-11812d56ca06">

I'd like that because I've _never_ needed or wanted to hide the minimap and to me the icon gives the impression of some other setting relating to showing or hiding something and so I'd just like to reduce the noise a little bit by not having it :)

**Comment by Nasller** [comment]
check this #43,it has an option

**Comment by G-Rath** [comment]
ah so there is:

<img width="261" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/3151613/790425b7-4bc2-476f-a393-d23c84bec6c0">

Could be worth adding that to the settings menu, but happy for this to be closed :)

**Comment by Nasller** [comment]
Will consider it.
