### ISSUE TITLE
When you open a large file, IDEA will freeze

### ISSUE THREAD

**Issue by Sherlockwxd** [Nasller/CodeGlancePro#93]
1. Which Glance version and IDEA version?
IDEA 2023.2
2. Could you show Glance config picture and minimap picture?

3. What steps will reproduce the issue?
open a large file

**Comment by Nasller** [comment]
please try the latest nightly build

**Comment by Sherlockwxd** [comment]
I updated to 1.7.1, but the bug still exists

![image](https://github.com/Nasller/CodeGlancePro/assets/48196121/bdffcff3-6299-4e75-b2d3-e9c3c75ebb00)

**Comment by Nasller** [comment]
sorry,i mean preview Channel

**Comment by Sherlockwxd** [comment]
Thanks，It's working！！！

**Comment by Nasller** [comment]
你的大文件是有多大

**Comment by Sherlockwxd** [comment]
中国老哥！！！快3000行代码

**Comment by Nasller** [comment]
打字卡？

**Comment by Nasller** [comment]
啥类型的文件呢？

**Comment by Sherlockwxd** [comment]
目前是http文件
![image](https://github.com/Nasller/CodeGlancePro/assets/48196121/8ec27886-560b-43b5-a9fc-17b60235a5ef)

**Comment by Nasller** [comment]
好的谢谢
